export default [
  { key: "./Misc/Charms/Skiller/Ama/Bow-Sk Life.d2i", value: "Sk0QAIAAZAAEOtY2AwKWf0m8MQXXSMUBJLwAAPIf" },
  { key: "./Misc/Charms/Skiller/Ama/Java-Sk Life.d2i", value: "Sk0QAIAAZAACOtY2AwKhdI/sMQ3YSMUBJLwEAPIf" },
  { key: "./Misc/Charms/Skiller/Ama/Passiv-Sk Life.d2i", value: "Sk0QAIAAZAAAOtY2AwJ3/EyKMZXXSMUBJLwCAPIf" },
  { key: "./Misc/Charms/Skiller/Assa/Martial Arts-Sk Life.d2i", value: "Sk0QAIAAZAAKOtY2A4Jy/mjZMQX8SMUBJLxkAPIf" },
  { key: "./Misc/Charms/Skiller/Assa/Shadow-Sk Life.d2i", value: "Sk0QAIAAZAAIOtY2AwIXt2ntMYX7SMUBJLxiAPIf" },
  { key: "./Misc/Charms/Skiller/Assa/Trap-Sk Life.d2i", value: "Sk0QAIAAZAAGOtY2AwJGt2qWMQ37SMUBJLxgAPIf" },
  { key: "./Misc/Charms/Skiller/Barb/Combat-Sk Life.d2i", value: "Sk0QAIAAZACgOtY2A4KNvhy5MQ3vSMUBJLxAAPIf" },
  { key: "./Misc/Charms/Skiller/Barb/Cry-Sk Life.d2i", value: "Sk0QAIAAZACkOtY2AwKhdFGBMQ3wSMUBJLxEAPIf" },
  { key: "./Misc/Charms/Skiller/Barb/Mastery-Sk Life.d2i", value: "Sk0QAIAAZACiOtY2A4Lpik3HMZXvSMUBJLxCAPIf" },
  { key: "./Misc/Charms/Skiller/Dru/Elemental-Sk Life.d2i", value: "Sk0QAIAAZACqOtY2AwJyb1vsMRX2SMUBJLxUAPIf" },
  { key: "./Misc/Charms/Skiller/Dru/Shape-Sk Life.d2i", value: "Sk0QAIAAZACoOtY2AwIwYtSMMY31SMUBJLxSAPIf" },
  { key: "./Misc/Charms/Skiller/Dru/Summon-Sk.d2i", value: "Sk0QAIAAZACmOtY2A4K3MRyuMRX1SMUBJLxQAPIf" },
  { key: "./Misc/Charms/Skiller/Necro/Bone-PSN-Sk Life.d2i", value: "Sk0QAIAAZAACMtY2A4IQLuiBMZXjSMUBJLwiAPIf" },
  { key: "./Misc/Charms/Skiller/Necro/Curse-Sk Life.d2i", value: "Sk0QAIAAZAAAMtY2A4J+eCqqMRXjSMUBJLwgAPIf" },
  { key: "./Misc/Charms/Skiller/Necro/Summon-Sk Life.d2i", value: "Sk0QAIAAZAAEMtY2A4IP8pifMQ3kSMUBJLwkAPIf" },
  { key: "./Misc/Charms/Skiller/Pala/Combat-Sk Life.d2i", value: "Sk0QAIAAZAAGMtY2AwKx7/P4MQXpSMUBJLwwAPIf" },
  { key: "./Misc/Charms/Skiller/Pala/Defensive-Sk Life.d2i", value: "Sk0QAIAAZAAKMtY2AwJA992EMRXqSMUBJLw0APIf" },
  { key: "./Misc/Charms/Skiller/Pala/Offensive-Sk Life.d2i", value: "Sk0QAIAAZAAIMtY2AwKULe6TMYXpSMUBJLwyAPIf" },
  { key: "./Misc/Charms/Skiller/Sorc/Cold-Sk.d2i", value: "Sk0QAIAAZAAQMtY2A4KaglbiMQXeSMUBJLwUAPIf" },
  { key: "./Misc/Charms/Skiller/Sorc/Fire-Sk Life.d2i", value: "Sk0QAIAAZAAMMtY2AwLgQnP+MQXdSMUBJLwQAPIf" },
  { key: "./Misc/Charms/Skiller/Sorc/Light-Sk Life.d2i", value: "Sk0QAIAAZAAOMtY2A4JJWZSBMZXdSMUBJLwSAPIf" },
  { key: "./Misc/Charms/Small Charms/3 20 20 Charm.d2i", value: "Sk0QAIAAZAAgMtYWAwIenhngMQ2AdMUBGhMosDDAMAA1+A8=" },
  { key: "./Misc/Charms/Small Charms/Cold DMG Sc.d2i", value: "Sk0QAIAAZABkMtYWA4LTuq2mMZU4BYuNhw4y/wE=" },
  { key: "./Misc/Charms/Small Charms/Fire DMG Sc.d2i", value: "Sk0QAIAAZABEMtYWAwKdS+qlMYU+NQsMDRX/AQ==" },
  { key: "./Misc/Charms/Small Charms/Life Mana Sc.d2i", value: "Sk0QAIAAZABAMtYWAwJyndT1MY2XdMUBGgli/gM=" },
  { key: "./Misc/Charms/Small Charms/Life Resis Sc.d2i", value: "Sk0QAIAAZAAoMtYWA4LhHpLoMZWnZMUBGiduUtysuGlx8x8=" },
  { key: "./Misc/Charms/Small Charms/Light DMG Sc.d2i", value: "Sk0QAIAAZAAEMtYWAwIKGbHcMZVEZYsMYYz/" },
  { key: "./Misc/Charms/Small Charms/MF Resis Sc.d2i", value: "Sk0QAIAAZAACMtYWAwIaP+fEMQWhjMSJmxQ3K25a3EBZ+w8=" },
  { key: "./Misc/Charms/Small Charms/Psn DMG Sc.d2i", value: "Sk0QAIAAZAAAMtYWA4IMmaq+MZVK1UqOkUb69x8=" },
  { key: "./Misc/Craft/Amulet/Armageddon Slippers.d2i", value: "Sk0QIIAAZAAMEtZWBwK23jY0LQZgN8CUCQCNgNiBLQm0ThilMFph1MKIy+g/" },
  { key: "./Misc/Craft/Amulet/Gale Shell.d2i", value: "Sk0QIIAAZAASEtZWBwJ3W7cbLQbdS8AUagCNx8HH4YRRCqMVRi2MUoxxmf0H" },
  { key: "./Misc/Craft/Amulet/Shadow Wing II.d2i", value: "Sk0QAIAAZQAEGtZWB4JlS8IYMQ7Uq+5oBz0iLRygMWECEYSNgAIyPARQ3MBw/gM=" },
  { key: "./Misc/Craft/Amulet/Shadow Wing.d2i", value: "Sk0QAIAAZQACGtZWBwIY9gh0MQbUq/9Jj1/pBwiQHYgxYljRw0MARsNLBiD/AQ==" },
  { key: "./Misc/Craft/Amulet/Storm Circlet.d2i", value: "Sk0QIIAAZABMEtZWB4Lgnlg/LYZUH8CUCIBMGtSBKwm2TiStSEqRNEXigvkP" },
  { key: "./Misc/Craft/Amulet/Storm Hide.d2i", value: "Sk0QIIAAZABsEtZWBwIWnEs3LYZUI8AUCwCNgNiBLQm0ThilMFph1MKIi/E/" },
  { key: "./Misc/Craft/Boots/Bitter Brogues Leather Boots.d2i", value: "Sk0QIIAAZABIwiZGBwLuC/lnrSHMBmgAAwMwMgAyAlorrFJ0nWDi0voP" },
  { key: "./Misc/Craft/Boots/Grim Spur Chain Boots.d2i", value: "Sk0QIIAAZAAA0iZGB4JMl9Q5rVFaBpgABAQwsjEoADMrvlIgtTjikvoP" },
  { key: "./Misc/Craft/Boots/Rune Slippers Plate Boots.d2i", value: "Sk0QIIAAZABEgiZGBwIvnQMbraHqBsgABgYwMgAsAk4rtFJoneji4voP" },
  { key: "./Misc/Craft/Boots/Soul Shank Plate Boots.d2i", value: "Sk0QIIAAZAAEgiZGB4LAYeA3rcFLBsgABgYwMgAxAkgrwlJ8nRjjYvkP" },
  { key: "./Misc/Craft/Boots/Soul Spur Heavy Boots.d2i", value: "Sk0QIIAAZABAYidGB4JRi/5XrcFbBoCAgwMwMggZAMwIcK1wShHGpfUf" },
  { key: "./Misc/Craft/Boots/Viper Trample Chain Boots.d2i", value: "Sk0QIIAAZAAI0iZGB4Lo4YpjrfG5BpgABAQwsjEoAa0VWSewWgRxaf0H" },
  { key: "./Misc/Craft/Glove/Bow Blood Touch.d2i", value: "Sk0QIIAAZQAAimd3BgL9vFYcIiIaljNnVDZVgRY4ODiApAUUD0MXFCIFLwAAAXj5Dw==" },
  { key: "./Misc/Craft/Glove/Java Blood Touch.d2i", value: "Sk0QIIAAZQAEimd3BgIKxCdbIiIaljNnVDZVgRY4ODiApAUUD0MXFCIFLwEAAXj5Dw==" },
  { key: "./Misc/Craft/Glove/Martial Arts Blood Touch.d2i", value: "Sk0QIIAAZQAIimd3BoJmDtxoIiIaljNnVDZVgRY4ODiApAUUD0MXFCIFLxkAAXj5Dw==" },
  { key: "./Misc/Craft/Glove/Passive Gale Grasp.d2i", value: "Sk0QIIAAZAAgWtd2BoJr6JZkLaL7BWgCBAQuFmMEC4UuKB4DH4MoAScHXgEA+g8=" },
  { key: "./Misc/Craft/Glove/Soul Touch.d2i", value: "Sk0QIIAAZAAEWmd3BoJslaMFLcIbBliCgwMujC4oHgMfA0QFACkHWqQ4+g8=" },
  { key: "./Misc/Craft/Ring/Beast Master.d2i", value: "Sk0QAIAAZQAAKpfmBgK0LV4tMSZOye54mk1RJgAYOfAiAc0ECk7YpLBZYdPChscgWWGC4z8=" },
  { key: "./Misc/Craft/Ring/Bone Gyre.d2i", value: "Sk0QAIAAZQAgKpfmBoJqRgIaMQZTwPPYl4apFACQOXBkwhkphHgI/gM=" },
  { key: "./Misc/Craft/Ring/Death Knot.d2i", value: "Sk0QAIAAZQBGKpfmBoLal0o+MYbTvHJJDk/jSgAQCRA6MKOCcEE4YcRD8ElIVpjg+A8=" },
  { key: "./Misc/Craft/Ring/Doom Loop.d2i", value: "Sk0QIIAAZQBgKpfmBoJSBr95MQbSvV7ZkIVRIQAgOfAihc6KGx4BJWOW+g8=" },
  { key: "./Misc/Craft/Ring/Havoc Band.d2i", value: "Sk0QAIAAZMQMIJfmBgJ1IkJNMYbgwAYohgaIhEL4BABeBNAOhDnBkyKoxRIPhQ/Dfw==" },
  { key: "./Misc/Craft/Ring/Shadow Circle.d2i", value: "Sk0QAIAAZQAiKpfmBgImRlFhMQZUvTA5FtflHAAQOSAjAYmIgMfBh+E/" },
  { key: "./Misc/Craft/Ring/Skull Whorl.d2i", value: "Sk0QIIAAZQBIKpfmBgIYSM42MZ5QwYg5hzBpCwAQOSAjwYiIIAUSD4Gd/wE=" },
  { key: "./Misc/Craft/Ring/Storm Eye.d2i", value: "Sk0QAIAAZQBAKpfmBoIfdmcrMY5UvobpCvMhWQAYEeA6wCLFEI9DGs9/" },
  { key: "./Misc/Craft/Ring/Storm Master.d2i", value: "Sk0QAIAAZQAGKpfmBoLP7fUtMYZUye84DMmhXwCYOaBiAgYVBguBCwOGAI/ApwFU4D8=" },
  { key: "./Misc/Jewels/10 MF 40 Ed (red).d2i", value: "Sk0QAIAAZAAOolZ2BwL6GxqtMSVjkEQEFCiguP0H" },
  { key: "./Misc/Jewels/10 Min 15 Resis (red).d2i", value: "Sk0QAIAAZAAsolZ2BwK1TTTIMaWopEMF5YJyIihF0IqgFkGflP8=" },
  { key: "./Misc/Jewels/10 Min 40 Ed (orange).d2i", value: "Sk0QAIAAZABSolZ2BwIOAob9MRVjpEMEFCgqKBeUT8p/" },
  { key: "./Misc/Jewels/10-15 Dmg (red).d2i", value: "Sk0QAIAAZAAkolZ2BwLtvUGpMaVcpEMFxcLjgoLh8UkB9fgP" },
  { key: "./Misc/Jewels/15 Ias (green).d2i", value: "Sk0QAIAAZQBkqFZ2B4JTwPABHB0ArEKX0X8=" },
  { key: "./Misc/Jewels/15 Ias 15 Resis (blue).d2i", value: "Sk0QAIAAZAAMolZ2B4LZm8ThMY2orMKJoBRBK4JaBHUZ/Qc=" },
  { key: "./Misc/Jewels/15 Max 40 Ed (green).d2i", value: "Sk0QAIAAZAAyolZ2B4KpSxKUMR1jeEMEFCgsPDA8QD3+Aw==" },
  { key: "./Misc/Jewels/15 Requ 15 Resis (orange).d2i", value: "Sk0QAIAAZABqolZ2BwISMauhMZWozMWJoBRBK4JaBG2p+g8=" },
  { key: "./Misc/Jewels/15 Requ 40 Ed (orange).d2i", value: "Sk0QAIAAZABwolZ2BwKeqoH5MRVjzEUEFCi2VP0H" },
  { key: "./Misc/Jewels/15 Resis 1-100 Light (pink).d2i", value: "Sk0QAIAAZABMolZ2BwJg7QCQMYWocMqJoBRBK4JaBMkIyPgP" },
  { key: "./Misc/Jewels/15 Resis 10 MF (red).d2i", value: "Sk0QAIAAZAAIolZ2BwLHTuTaMaWokMSJoBRBK4JaBEFx+w8=" },
  { key: "./Misc/Jewels/20 Life 40 Ed (yellow).d2i", value: "Sk0QAIAAZAAwolZ2B4JF9UuhMS1jfMUBGhFQoPgP" },
  { key: "./Misc/Jewels/40 Ed 1-100 Light (orange).d2i", value: "Sk0QAIAAZAByolZ2BwJuDbe1MRVjcEoEFChkBGT8Bw==" },
  { key: "./Misc/Jewels/40 Ed 15 Ias (blue).d2i", value: "Sk0QAIAAZADgqlZ2B4JDVxSCMQ1jrEIEFCi6jP4D" },
  { key: "./Misc/Jewels/8 Min 15 Ias (red).d2i", value: "Sk0QAIAAZABEolZ2BwLnKuSnMaVTrEIF5ALSZfQJ+Q8=" },
  { key: "./Misc/Jewels/Fire Dmg 15 Resis (green).d2i", value: "Sk0QAIAAZABsolZ2B4K+ER3NMZ2oaMqJoBRBK4JaBMHIkPEf" },
  { key: "./Misc/Jewels/Fire-Dmg 40 Ed (pink).d2i", value: "Sk0QAIAAZAAQolZ2BwJY+5m9MQVjaEoEFChgZMj4Dw==" },
  { key: "./Misc/Misc/Arrows.d2i", value: "Sk0QIIAAZAAiEhZnBwJhnLhX7RBe/wM=" },
  { key: "./Misc/Misc/Bolts.d2i", value: "Sk0QIIAAZAAkMhZnB4Ktowga7RD6/gM=" },
  { key: "./Misc/Misc/Identify Book.d2i", value: "Sk0QIIAAZABAkia2BgIRAe9LrRBQ+A8=" },
  { key: "./Misc/Misc/Identify Scroll.d2i", value: "Sk0QIKAAZABGkjY3BgI=" },
  { key: "./Misc/Misc/Skeleton Key.d2i", value: "Sk0QAIAAZQBuslaWB4KX+TPssIDBfw==" },
  { key: "./Misc/Misc/Town Portal Book.d2i", value: "Sk0QIIAAZAAAQie2BgLLDjEarQBQ+A8=" },
  { key: "./Misc/Misc/Town Portal Scroll.d2i", value: "Sk0QIKAAZAAmQjc3BgI=" },
  { key: "./Misc/Potions/Antidote Potion.d2i", value: "Sk0QIKAAZAAAkgc3BwI=" },
  { key: "./Misc/Potions/Full Rejuv Potion.d2i", value: "Sk0QIKAAZABiImfHBgI=" },
  { key: "./Misc/Potions/Greater Healing Potion.d2i", value: "Sk0QIKAAZAAgggZXAwI=" },
  { key: "./Misc/Potions/Greater Mana Potion.d2i", value: "Sk0QIKAAZAAi0gZXAwI=" },
  { key: "./Misc/Potions/Rejuv Potion.d2i", value: "Sk0QIKAAZABgImc3BwI=" },
  { key: "./Misc/Potions/Stamina Potion.d2i", value: "Sk0QIKAAZAACYgc3BwI=" },
  { key: "./Misc/Potions/Thawing Potion.d2i", value: "Sk0QIKAAZAAEctc2BwI=" },
  { key: "./Misc/Quest/Act 1/Inifuss Scroll.d2i", value: "Sk0QAKAAZQAEIrY2ByI=" },
  { key: "./Misc/Quest/Act 1/Malus.d2i", value: "Sk0QAIAAZQBSgkbWBgLIIa8e4/H/blyQ9T8=" },
  { key: "./Misc/Quest/Act 1/Wirt's Leg.d2i", value: "Sk0QCIAAZQAOwlZ2BgLvfpczpkDIxJD1Pw==" },
  { key: "./Misc/Quest/Act 2/Amulet.d2i", value: "Sk0QAIAAZQBGYpcGB4JzblDb6YU9cEBFApUWS2T9Dw==" },
  { key: "./Misc/Quest/Act 2/Book of Skill.d2i", value: "Sk0QIKAAZAAAEjY3BwI=" },
  { key: "./Misc/Quest/Act 2/Cube.d2i", value: "Sk0QAIAAZQAAIvaGBwLcL+bQhuA/" },
  { key: "./Misc/Quest/Act 2/Staff.d2i", value: "Sk0QAIAAZQAI0jZnBoIxTbaa6sEHWlac4EnBs4KnBU8XI1n/Aw==" },
  { key: "./Misc/Quest/Act 3/Brain.d2i", value: "Sk0QAKAAZQDiGicmByI=" },
  { key: "./Misc/Quest/Act 3/Complete Flail.d2i", value: "Sk0QIIAAZQAKEmcmA4KntBOKwAEIPDBMQEFGgAIPgw9DFyNZ/wM=" },
  { key: "./Misc/Quest/Act 3/Eye.d2i", value: "Sk0QAKAAZQDgGleWByI=" },
  { key: "./Misc/Quest/Act 3/Flail.d2i", value: "Sk0QAIAAZQAIEmcWAwIlse716vEHPDZMQEFGQEEXI1n/Aw==" },
  { key: "./Misc/Quest/Act 3/Gidbinn.d2i", value: "Sk0QAIAAZQBEcjYzAwLzubz36fH/PCSQ9T8=" },
  { key: "./Misc/Quest/Act 3/Gold Bird.d2i", value: "Sk0QIKAAZQAEcjZDAyI=" },
  { key: "./Misc/Quest/Act 3/Heart.d2i", value: "Sk0QAKAAZQDkGocmByI=" },
  { key: "./Misc/Quest/Act 3/Lam Esen's Tome.d2i", value: "Sk0QAKAAZQAKIiYmBiI=" },
  { key: "./Misc/Quest/Act 4/Hammer.d2i", value: "Sk0QAIAAZQAIgmaGBgIWV90f7OEHbmB8aMEJLRgFFMj6Hw==" },
  { key: "./Misc/Quest/Act 4/Soul Stone.d2i", value: "Sk0QIKAAZQBo0jY3ByI=" },
  { key: "./Misc/Quest/Act 5/Malah's Potion.d2i", value: "Sk0QIIAAZQBqkjZWBoKX8i5up4Cs/wE=" },
  { key: "./Misc/Quest/Act 5/Scroll of Malah.d2i", value: "Sk0QIKAAZQAIQicnAyI=" },
  { key: "./Misc/Quest/Bugged Tal Rasha's.d2i", value: "Sk0QCIAAZQBgWkeHBgLJQM7ccfEETnRzI8IHzZDIOKGVQmuFVgstMK0RzxaUP/qfxvMf" },
  { key: "./Misc/Quest/Essences & Token/Burning Essence of Terror (Red).d2i", value: "Sk0QIKAAZABgIlZGBwI=" },
  { key: "./Misc/Quest/Essences & Token/Charged Essence of Hatred (Yellow).d2i", value: "Sk0QIKAAZABAMlaGBgI=" },
  { key: "./Misc/Quest/Essences & Token/Festering Essence of Destruction (Green).d2i", value: "Sk0QIKAAZAACYlZGBgI=" },
  { key: "./Misc/Quest/Essences & Token/Token of Absolution.d2i", value: "Sk0QIKAAZAAAQvcWBgI=" },
  { key: "./Misc/Quest/Essences & Token/Twisted Essence of Suffering (Blue).d2i", value: "Sk0QIKAAZAAgQlc2BwI=" },
  { key: "./Misc/Quest/Keys & Organs/Baal's Eye.d2i", value: "Sk0QIKAAZAAgIlaWBwI=" },
  { key: "./Misc/Quest/Keys & Organs/Destruction.d2i", value: "Sk0QAIAAZQAEArc2A4L8EpSBr+A/" },
  { key: "./Misc/Quest/Keys & Organs/Diablo's Horn.d2i", value: "Sk0QIKAAZAAAQobmBgI=" },
  { key: "./Misc/Quest/Keys & Organs/Hate.d2i", value: "Sk0QAIAAZQAEArcmAwLI3VgNqOA/" },
  { key: "./Misc/Quest/Keys & Organs/Mephisto's Brain.d2i", value: "Sk0QIKAAZABA0iYmBwI=" },
  { key: "./Misc/Quest/Keys & Organs/Terror.d2i", value: "Sk0QAIAAZQAGArcWAwKxk0YMqeA/" },
  { key: "./Misc/Quest/Standard of Heroes.d2i", value: "Sk0QAIAAZQAmO0dHBoIAMxvS8fH//gM=" },
  { key: "./Misc/Quest/Trap Suwayyah.d2i", value: "Sk0QKIAAZAAKchMmBwIA5Ggb7RAwMIYXDMDWPNx/" },
  { key: "./Misc/Rares/Amulet/Armageddon Fletch.d2i", value: "Sk0QIIAAZAAsEtZWBwJNkxFMrQVgFsCUCIBMGtSBKwm2TiSlSFqR1CKJS+o/" },
  { key: "./Misc/Rares/Amulet/Fiendra Sunder.d2i", value: "Sk0QIIAAZAAyEtZWBwL3hZoprQVcB8AUCsAMGM+BLQmyBNC4tP4D" },
  { key: "./Misc/Rares/Amulet/Grim Necklace.d2i", value: "Sk0QIIAAZABSEtZWBwIxLBoPrYVSQ8CUCUCMgFmCKztXIHEZnhhKkdQi6D8=" },
  { key: "./Misc/Rares/Amulet/Imp Brow.d2i", value: "Sk0QIIAAZAByEtZWB4L3EYE1rYVbIcAUCsAMj4OPwxToxFGKoxVHLY64TP4D" },
  { key: "./Misc/Rares/Amulet/Order Noose.d2i", value: "Sk0QIIAAZAAOEtZWB4I8J4VfrYXiQsAUCMCMgFaCnBVCXIYnlFIgtUD6Dw==" },
  { key: "./Misc/Rares/Ring/Beast Circle.d2i", value: "Sk0QIIAAZABOIpfmBoJJxitrrQVOPQAPgo/DirEUPVAGuUj+Aw==" },
  { key: "./Misc/Rares/Ring/Bitter Turn.d2i", value: "Sk0QIIAAZABuIpfmBgKovIdArQXhPgCPwoRBBLRSNAFo4eJKwPIf" },
  { key: "./Misc/Rares/Ring/Blood Whorl.d2i", value: "Sk0QIIAAZAAuIpfmBoJSQVQ2rQVRQQAPg4/CiqYTRFAIuTT+Aw==" },
  { key: "./Misc/Rares/Ring/Bone Master.d2i", value: "Sk0QIIAAZAAAKpfmBoJB9KokrQVTSUAaT4K4E0EpglYEtQhKYTUi4OL6Dw==" },
  { key: "./Misc/Rares/Ring/Corruption Grip.d2i", value: "Sk0QIIAAZABwIpfmBgLJ4jtarYVkLwAPw4RKfBxOBKUIWhHUIugEFhfXE0//AQ==" },
  { key: "./Misc/Rares/Ring/Eagle Circle.d2i", value: "Sk0QIIAAZABQIpfmBgJo5D5ZrYVOPQCPwoQhfBxOBKUIWhHUImgFGhfXfw==" },
  { key: "./Misc/Rares/Ring/Shadow Spiral.d2i", value: "Sk0QIIAAZAAwIpfmBoIH75dWrQVUPwCPAgAXH4cUY1DguLiy2H8=" },
  { key: "./Misc/Rares/Ring/Viper Whorl.d2i", value: "Sk0QIIAAZAAQIpfmBgLF/Z1qrYVPQQAPwwQLDhw5EZQiaEVQi6AEQFxcPg7/AQ==" },
  { key: "./Misc/Runes/Amn Rune.d2i", value: "Sk0QAKAAZAAAIhcTAwI=" },
  { key: "./Misc/Runes/Ber Rune.d2i", value: "Sk0QAKAAZAACIjcDAwI=" },
  { key: "./Misc/Runes/Cham Rune.d2i", value: "Sk0QAKAAZAAEIjcjAwI=" },
  { key: "./Misc/Runes/Dol Rune.d2i", value: "Sk0QAKAAZAAGIhdDAwI=" },
  { key: "./Misc/Runes/El Rune.d2i", value: "Sk0QAKAAZAAIIgcTAwI=" },
  { key: "./Misc/Runes/Eld Rune.d2i", value: "Sk0QAKAAZAAKIgcjAwI=" },
  { key: "./Misc/Runes/Eth Rune.d2i", value: "Sk0QAKAAZAAMIgdTAwI=" },
  { key: "./Misc/Runes/Fal Rune.d2i", value: "Sk0QAKAAZAAOIheTAwI=" },
  { key: "./Misc/Runes/Gul Rune.d2i", value: "Sk0QAKAAZAAgIidTAwI=" },
  { key: "./Misc/Runes/Hel Rune.d2i", value: "Sk0QAKAAZAAiIhdTAwI=" },
  { key: "./Misc/Runes/Io Rune.d2i", value: "Sk0QIKAAZABAIhdjAwI=" },
  { key: "./Misc/Runes/Ist Rune.d2i", value: "Sk0QAKAAZAAkIidDAwI=" },
  { key: "./Misc/Runes/Ith Rune.d2i", value: "Sk0QAKAAZAAmIgdjAwI=" },
  { key: "./Misc/Runes/Jah Rune.d2i", value: "Sk0QAKAAZAAoIjcTAwI=" },
  { key: "./Misc/Runes/Ko Rune.d2i", value: "Sk0QAKAAZAAqIheDAwI=" },
  { key: "./Misc/Runes/Lem Rune.d2i", value: "Sk0QAKAAZAAsIicDAwI=" },
  { key: "./Misc/Runes/Lo Rune.d2i", value: "Sk0QAKAAZAAuIieDAwI=" },
  { key: "./Misc/Runes/Lum Rune.d2i", value: "Sk0QAKAAZABAIhdzAwI=" },
  { key: "./Misc/Runes/Mal Rune.d2i", value: "Sk0QAKAAZABCIiczAwI=" },
  { key: "./Misc/Runes/Nef Rune.d2i", value: "Sk0QAKAAZABEIgdDAwI=" },
  { key: "./Misc/Runes/Ohm Rune.d2i", value: "Sk0QAKAAZABGIidzAwI=" },
  { key: "./Misc/Runes/Ort Rune.d2i", value: "Sk0QAKAAZABIIgeTAwI=" },
  { key: "./Misc/Runes/Po Rune.d2i", value: "Sk0QAKAAZABKIhdjAwI=" },
  { key: "./Misc/Runes/Pul Rune.d2i", value: "Sk0QAKAAZABMIicTAwI=" },
  { key: "./Misc/Runes/Ral Rune.d2i", value: "Sk0QAKAAZABOIgeDAwI=" },
  { key: "./Misc/Runes/Shael Rune.d2i", value: "Sk0QAKAAZABgIhczAwI=" },
  { key: "./Misc/Runes/Sol Rune.d2i", value: "Sk0QAKAAZABiIhcjAwI=" },
  { key: "./Misc/Runes/Sur Rune.d2i", value: "Sk0QAKAAZABkIieTAwI=" },
  { key: "./Misc/Runes/Tal Rune.d2i", value: "Sk0QAKAAZABmIgdzAwI=" },
  { key: "./Misc/Runes/Thul Rune.d2i", value: "Sk0QAKAAZABoIhcDAwI=" },
  { key: "./Misc/Runes/Tir Rune.d2i", value: "Sk0QAKAAZABqIgczAwI=" },
  { key: "./Misc/Runes/Um Rune.d2i", value: "Sk0QAKAAZABsIicjAwI=" },
  { key: "./Misc/Runes/Vex Rune.d2i", value: "Sk0QAKAAZABuIidjAwI=" },
  { key: "./Misc/Runes/Zod Rune.d2i", value: "Sk0QAKAAZAAQIjczAwI=" },
  {
    key: "./Runewords/Armor/Class Specific/Bone (AP).d2i",
    value: "Sk0QCIAEZACoWkcHB7LGUfF+7RARKBbi4TEQHiwZ/U9gO0UyplDxSKYQ8fgPSk0QAKAAZBgAIBcjAwJKTRAAoABkGAIgJyMDAkpNEACgAGQYBCAnIwMC",
  },
  {
    key: "./Runewords/Armor/Class Specific/Enlightenment (AP).d2i",
    value: "Sk0QCIAEZACgWkcHBzIyzSs57RAeKBbi4TEQHiwZ/Z8ShSkRGHteKCR7XCj8B0pNEACgAGQYACAnEwMCSk0QAKAAZBgCIAeDAwJKTRAAoABkGAQgFyMDAg==",
  },
  {
    key: "./Runewords/Armor/Class Specific/Myth (AP).d2i",
    value: "Sk0QCIAEZAAIWkcHB7L9ht8U7RA4KBbi4TEQHiwZ/VeCTqGMBYkokgWCDP4DSk0QAKAAZBgAIBdTAwJKTRAAoABkGAIgFxMDAkpNEACgAGQYBCAHQwMC",
  },
  {
    key: "./Runewords/Armor/Class Specific/Peace (AP).d2i",
    value: "Sk0QCIAEZACkWkcHBzKix8AF7ZA9KBbi4TEQHiwZ/Z8ChUkgGHtAECQrIiD8B0pNEACgAGQYACAXMwMCSk0QAKAAZBgCIBcDAwJKTRAAoABkGAQgFxMDAg==",
  },
  {
    key: "./Runewords/Armor/Class Specific/Principle (AP).d2i",
    value: "Sk0QCIAEZAAEWkcHB7LXlYlL7ZBDKBbi4TEQHiwZ/Z8yGSvKIOsxcsDWf0pNEACgAGQYACAHgwMCSk0QAKAAZBgCICdTAwJKTRAAoABkGAQgByMDAg==",
  },
  {
    key: "./Runewords/Armor/Class Specific/Rain (AP).d2i",
    value: "Sk0QCIAEZAAEUkcHBzLPisc67RBHKBbi4TEQHiwZ/U9gO6Uy9sBTSPasU/gPSk0QAKAAZBgAIAeTAwJKTRAAoABkGAIgJzMDAkpNEACgAGQYBCAHYwMC",
  },
  {
    key: "./Runewords/Armor/Class Specific/Treachery (AP).d2i",
    value: "Sk0QCIAEZAAAWkcHB7KfPl8a7ZBWKBbi4TEQHiwZ/Z9idQkaeyzKJHsWKvwHSk0QAKAAZBgAIBczAwJKTRAAoABkGAIgFwMDAkpNEACgAGQYBCAnAwMC",
  },
  {
    key: "./Runewords/Armor/Chains of Honor (AP).d2i",
    value:
      "Sk0QCIAEZABmWkcHB0JKffA07RAUKBbi4UEQHiwZ/QdAA8HICbIUZCvIWpDxQOThpgfPH/0HSk0QAKAAZBgAIBdDAwJKTRAAoABkGAIgJyMDAkpNEACgAGQYBCA3AwMCSk0QAKAAZBgGICdDAwI=",
  },
  {
    key: "./Runewords/Armor/Chains of Honor (AP, Eth).d2i",
    value:
      "Sk0QCMAEZAAEUkcHB0JKffA07RAUKBzj4UEQHiwZ/QdAA8HICbIUZCvIWpDxQOThpgfPH/0HSk0QAKAAZBgAIBdDAwJKTRAAoABkGAIgJyMDAkpNEACgAGQYBCA3AwMCSk0QAKAAZBgGICdDAwI=",
  },
  {
    key: "./Runewords/Armor/Duress (AP).d2i",
    value: "Sk0QCIAEZAAAUkcHBzJs5ut67RAcKBbi4TEQHiwZ/YeALAIFCjZKCsmMQR0KIXpoAvwHSk0QAKAAZBgAIBczAwJKTRAAoABkGAIgJyMDAkpNEACgAGQYBCAXAwMC",
  },
  {
    key: "./Runewords/Armor/Enigma (AP).d2i",
    value: "Sk0QCIAEZGQGUEcHBzL625xu7ZAdKBbi2TEQHny4wP8PBLPiABMMYyP4I24GPOQ/Sk0QAKAAZBgAIDcTAwJKTRAAoABkGAIgB2MDAkpNEACgAGQYBCA3AwMC",
  },
  {
    key: "./Runewords/Armor/Enigma (AP, Eth).d2i",
    value: "Sk0QCMAEZAAIUkcHBzL625xu7ZAdKBzj4TEQHny4wP8PBLPiABMMYyP4I24GPOQ/Sk0QAKAAZBgAIDcTAwJKTRAAoABkGAIgB2MDAkpNEACgAGQYBCA3AwMC",
  },
  {
    key: "./Runewords/Armor/Fortitude (AP).d2i",
    value:
      "Sk0QCIAEZAAMUkcHB8LGiJQ27ZAhKBbi4UEQHiwZ/YeALAJLliegUkCtgGoBlaYlh0n28EDBxvwHSk0QAKAAZBgAIAcTAwJKTRAAoABkGAIgFyMDAkpNEACgAGQYBCAXQwMCSk0QAKAAZBgGICeDAwI=",
  },
  {
    key: "./Runewords/Armor/Fortitude (AP, Eth).d2i",
    value:
      "Sk0QCMAEZAAQUkcHB8LCOVBE7ZAhKBzj4UEQHiwZ/YeALAJLliegUkCtgGoBlaYlh0n28EDBBv0HSk0QAKAAZBgAIAcTAwJKTRAAoABkGAIgFyMDAkpNEACgAGQYBCAXQwMCSk0QAKAAZBgGICeDAwI=",
  },
  {
    key: "./Runewords/Armor/Wealth (DS).d2i",
    value: "Sk0QCIAEZAAAUleXBjIbfBxz7ZBcKBSgoDD/n3iFgvwfSk0QAKAAZBgAICcDAwJKTRAAoABkGAIgF4MDAkpNEACgAGQYBCAHMwMC",
  },
  {
    key: "./Runewords/Helmet/Delirium (Corona).d2i",
    value:
      "Sk0QCIAEZAAAUifnBrLUNQVY7RBPFRSQATD/Pzzkj4xJUSySNU04kjkRGZLJXgWYRVbw8PwHSk0QAKAAZBgAICcDAwJKTRAAoABkGAIgJ0MDAkpNEACgAGQYBCAXYwMC",
  },
  {
    key: "./Runewords/Helmet/Dream (Corona).d2i",
    value:
      "Sk0QCIAEZAAAUifnBrJl+gVa7ZACeK+QkTFLRhAe/L9k542RfTBHtuKEUQqjFUYtjKD0JXuiUPwHSk0QAKAAZBgAIBdjAwJKTRAAoABkGAIgNxMDAkpNEACgAGQYBCAnEwMC",
  },
  {
    key: "./Runewords/Helmet/Lore (Corona).d2i",
    value: "Sk0QCIAEZABIUifnBqL9bjJm7ZAyKBSQkSH/A6iy2J8oEvwHSk0QAKAAZBgAIAeTAwJKTRAAoABkGAIgFyMDAg==",
  },
  {
    key: "./Runewords/Helmet/Nadir (Corona).d2i",
    value: "Sk0QCIAEZABEUifnBiL3p+Ei7ZA4KBSQkSH/AZRAkPGBAk+GZAlmDUIJCf8BSk0QAKAAZBgAIAdDAwJKTRAAoABkGAIgBzMDAg==",
  },
  {
    key: "./Runewords/Helmet/Radiance (Corona).d2i",
    value: "Sk0QCIAEZABAUifnBrLTBJpk7ZBGKBSQkTH/A6gGqBIEQVgyYsiS/wFKTRAAoABkGAAgB0MDAkpNEACgAGQYAiAXIwMCSk0QAKAAZBgEIAdjAwI=",
  },
  {
    key: "./Runewords/Merc/Destruction (CA, Eth).d2i",
    value:
      "Sk0QCMAEZAAIegMXBlKPVrBD7ZAZKEFBKsKDB0tG/yN49UqDjFadwDALhkexFgeysaucgjGGnst/Sk0QAKAAZBgAICdjAwJKTRAAoABkGAIgJ4MDAkpNEACgAGQYBCA3AwMCSk0QAKAAZBgGIDcTAwJKTRAAoABkGAggF4MDAg==",
  },
  {
    key: "./Runewords/Merc/Doom (CA, Eth).d2i",
    value:
      "Sk0QCMAEZACIegMXBtJ7dv057RAaKEFBKgIKFE8d/kfAiLFLsE7gjy7JYcYkegpPXf4DSk0QAKAAZBgAIBdTAwJKTRAAoABkGAIgJ3MDAkpNEACgAGQYBCAnIwMCSk0QAKAAZBgGICeDAwJKTRAAoABkGAggNyMDAg==",
  },
  {
    key: "./Runewords/Merc/Infinity (CA, Eth).d2i",
    value:
      "Sk0QCMAEZAAAegMXBsJ9vvES7RArKEFBKMKDB0tG/yMULQrmdmkPI0bVIGNWrePh8Y1wevMfSk0QAKAAZBgAIDcDAwJKTRAAoABkGAIgJzMDAkpNEACgAGQYBCA3AwMCSk0QAKAAZBgGICdDAwI=",
  },
  {
    key: "./Runewords/Merc/Insight (CA, Eth).d2i",
    value:
      "Sk0QCMAEZAAAegMXBkLTB0U27RAsKEFB6D+AkgAlAaUBpQgECULZC5PASHO74/ASnvgfSk0QAKAAZBgAIAeDAwJKTRAAoABkGAIgBzMDAkpNEACgAGQYBCAHcwMCSk0QAKAAZBgGIBcjAwI=",
  },
  {
    key: "./Runewords/Merc/Obedience (CA, Eth).d2i",
    value:
      "Sk0QCMAEZAAEcgMXBtLIsBg37ZA6KAAV4cGDJaP/EeTK/WCTE1ApoFZAtYAaw0OEIlbR4Gma8R9KTRAAoABkGAAgF1MDAkpNEACgAGQYAiAXgwMCSk0QAKAAZBgEIBcDAwJKTRAAoABkGAYgB1MDAkpNEACgAGQYCCAXkwMC",
  },
  {
    key: "./Runewords/Merc/Phoenix (CA, Eth).d2i",
    value:
      "Sk0QCMAEZIQIcAMXBkJ8B/M+7RBAKEFBKMKDB0tG/yNAhgwC8qPKJT7NmBUO6hjqArkpx39KTRAAoABkGAAgJ2MDAkpNEACgAGQYAiAnYwMCSk0QAKAAZBgEICeDAwJKTRAAoABkGAYgNxMDAg==",
  },
  {
    key: "./Runewords/Merc/Pride (CA, Eth).d2i",
    value:
      "Sk0QCMAEZAAEcgMXBkIvwPUH7RBDKEFBKMKDB0tG/2XIGCkx7wC9FIcmi2bIvHvmIf8BSk0QAKAAZBgAIDcjAwJKTRAAoABkGAIgJ5MDAkpNEACgAGQYBCAXYwMCSk0QAKAAZBgGICeDAwI=",
  },
  {
    key: "./Runewords/Merc/Rift (CA, Eth).d2i",
    value:
      "Sk0QCMAEZAAMcgMXBkKMnFVO7RBJKEFBKMKDB0tG/wGoBFAJUA1QweChRQNUnxxzWAUExBhUD4XZwwQKyn9KTRAAoABkGAAgF1MDAkpNEACgAGQYAiAXgwMCSk0QAKAAZBgEICcDAwJKTRAAoABkGAYgJ1MDAg==",
  },
  {
    key: "./Runewords/Shield/Dragon (Mon).d2i",
    value:
      "Sk0QCIAEZAAEWpdGB7LUeSBM7ZAaKJ6wsjIQHlB4lozMjP4DKAlQElAaUPogFxDmLplxxh4fGMkkiyjchv9KTRAAoABkGAAgJ5MDAkpNEACgAGQYAiAngwMCSk0QAKAAZBgEIBcjAwI=",
  },
  {
    key: "./Runewords/Shield/Dragon (Zaka).d2i",
    value:
      "Sk0QCIAEZABkChdWBjKGv3kl7ZAaKMsICjIQHkR48IDCc+IrxdeKrxZfS0ZmRv8BlAQoCSgNKH2QCwhzl8w4Y48PjGSSRRRuw39KTRAAoABkGAAgJ5MDAkpNEACgAGQYAiAngwMCSk0QAKAAZBgEIBcjAwI=",
  },
  {
    key: "./Runewords/Shield/Dream (Mon).d2i",
    value:
      "Sk0QCIAEZACIWpdGBzLm6K9z7ZAbKJ6wsjIQHlB4lozMjP5/MMcJoxRGK4xaGEHpGyO7ZOcle6JQZCv+A0pNEACgAGQYACAXYwMCSk0QAKAAZBgCIDcTAwJKTRAAoABkGAQgJxMDAg==",
  },
  {
    key: "./Runewords/Shield/Dream (Zaka).d2i",
    value:
      "Sk0QCIAEZAAIChdWBjIOjqZE7ZAbKMsICjIQHkR48IDCc+IrxdeKrxZfS0ZmRv8/mOOEUQqjFUYtjKD0jZFdsvOSPVEoshX/AUpNEACgAGQYACAXYwMCSk0QAKAAZBgCIDcTAwJKTRAAoABkGAQgJxMDAg==",
  },
  {
    key: "./Runewords/Shield/Exil (Vortex, Eth).d2i",
    value:
      "Sk0QCMAEZAAEChdmBkIaN5YD7ZAfKF7R0kIQHkR48IDCc+IrxdeKrxZfZjz/IRA0IzMULqFxvDIAZKyQ4sEv+w9KTRAAoABkGAAgJ2MDAkpNEACgAGQYAiAncwMCSk0QAKAAZBgEICdDAwJKTRAAoABkGAYgF0MDAg==",
  },
  {
    key: "./Runewords/Shield/Phoenix (Mon).d2i",
    value:
      "Sk0QCIAEZAAEUpdGB0JuvRwk7RBAAJ6QkkIqygEpKMr/Y6gLZGNWOKhLfB4IyBEgQ5bp9KjyH0pNEACgAGQYACAnYwMCSk0QAKAAZBgAICdjAwJKTRAAoABkGAAgJ4MDAkpNEACgAGQYACA3EwMC",
  },
  {
    key: "./Runewords/Shield/Spirit (Mon).d2i",
    value:
      "Sk0QCIAEZACAWpdGB8JwgktR7ZBNKJ6wskIQHlB4lozMjP4PsCWABKFvzDLN7Y8mIf4DSk0QAKAAZBgAIAdzAwJKTRAAoABkGAIgFwMDAkpNEACgAGQYBCAHkwMCSk0QAKAAZBgGIBcTAwI=",
  },
  {
    key: "./Runewords/Shield/Spirit (Zaka).d2i",
    value:
      "Sk0QCIAEZAAAChdWBkIoKXx47ZBNKMsICkIQHkR48IDCc+IrxdeKrxZfS0ZmRv8H2BJAgtA3Zpnm9keTEP8BSk0QAKAAZBgAIAdzAwJKTRAAoABkGAIgFwMDAkpNEACgAGQYBCAHkwMCSk0QAKAAZBgGIBcTAwI=",
  },
  {
    key: "./Runewords/Shield/Splendor (BS).d2i",
    value: "Sk0QCIAEZAAQ4lZmBqLcn2147RBOKJ6goCAQHiwZremiNVT0HwKZJ5ag4GU5M6g0nj/5D0pNEACgAGQYACAHUwMCSk0QAKAAZBgCIBdzAwI=",
  },
  {
    key: "./Runewords/Shield/Splendor (Mon).d2i",
    value: "Sk0QCIAEZAAAWpdGB6JhJ3I27RBOKJ6wsiIQHiwZ/YdA5oklKHhZzgwqjedP/gNKTRAAoABkGAAgB1MDAkpNEACgAGQYAiAXcwMC",
  },
  {
    key: "./Runewords/Shield/Splendor (Zaka).d2i",
    value: "Sk0QCIAEZAAMAhdWBiKQgH9i7RBOKMsICiIQHiwZnfhK8bXiq8XXfwhknliCgpflzKDSeP7kP0pNEACgAGQYACAHUwMCSk0QAKAAZBgCIBdzAwI=",
  },
  {
    key: "./Runewords/Weapon/Axe/Beast (BA).d2i",
    value:
      "Sk0QCIAEZACkenMXBtKYqR927RAPKBoaKsKDB0tG/wEgRXDosAsvDLghDLnhkp7ErLmnoOA/Sk0QAKAAZBgAIDcDAwJKTRAAoABkGAIgBzMDAkpNEACgAGQYBCAnIwMCSk0QAKAAZBgGICczAwJKTRAAoABkGAggF3MDAg==",
  },
  {
    key: "./Runewords/Weapon/Axe/Doom (BA).d2i",
    value:
      "Sk0QCIAEZAAIenMXBlKHMMsz7RAaKBoaKsKDB/8jAAXaJVgn8EeX5DBjEj2Fpzz/AUpNEACgAGQYACAXUwMCSk0QAKAAZBgCICdzAwJKTRAAoABkGAQgJyMDAkpNEACgAGQYBiAngwMCSk0QAKAAZBgIIDcjAwI=",
  },
  {
    key: "./Runewords/Weapon/Axe/Eternity (BA, Eth).d2i",
    value:
      "Sk0QCMAEZACgenMXBlI5AtAs7RAfKBoaKsKDB0tG/yPYtLkBQolrKYRppsyQL7Cw/gNKTRAAoABkGAAgFxMDAkpNEACgAGQYAiA3AwMCSk0QAKAAZBgEICdDAwJKTRAAoABkGAYgFyMDAkpNEACgAGQYCCAnkwMC",
  },
  {
    key: "./Runewords/Weapon/Bows/Brand (GMB).d2i",
    value:
      "Sk0QCIAEZAAAEtY2BkK+2M1o7RASKAAU4cGDJSNeAAD6H4Eq1SiBOoE8Xj0FjElUkJM5Qoz+A0pNEACgAGQYACA3EwMCSk0QAKAAZBgCICeDAwJKTRAAoABkGAQgJzMDAkpNEACgAGQYBiAnUwMC",
  },
  {
    key: "./Runewords/Weapon/Bows/Brand (HB).d2i",
    value:
      "Sk0QCIAEZAAoasN2B8KUImMJ7RASKAAU4cGDJaP/EahSjRKoE8jj1VPAmEQFOZkjxOg/Sk0QAKAAZBgAIDcTAwJKTRAAoABkGAIgJ4MDAkpNEACgAGQYBCAnMwMCSk0QAKAAZBgGICdTAwI=",
  },
  {
    key: "./Runewords/Weapon/Bows/Edge (GMB).d2i",
    value:
      "Sk0QCIAEZAAMEtY2BjLZyZBT7ZAcKAAT4cGDJSNeAAD6D0AlgEqAaoDqyqPLrU4gD2Q9LC+def8BSk0QAKAAZBgAIAczAwJKTRAAoABkGAIgB3MDAkpNEACgAGQYBCAXEwMC",
  },
  {
    key: "./Runewords/Weapon/Bows/Edge (HB).d2i",
    value:
      "Sk0QCIAEZAAQYsN2B7IShkBB7ZAcKAAT4cGDJaP/AFQCqASoBqiuPLrc6gTyQNbD8tKZ9x9KTRAAoABkGAAgBzMDAkpNEACgAGQYAiAHcwMCSk0QAKAAZBgEIBcTAwI=",
  },
  {
    key: "./Runewords/Weapon/Bows/Faith (GMB).d2i",
    value:
      "Sk0QCIAEZAAOEtY2BkJQ6kkL7RAgKAAU4cGDJSNeAAD6HwEjxhNBKYJWBLUIugP0jy7peZsCUPwHSk0QAKAAZBgAICdzAwJKTRAAoABkGAIgNxMDAkpNEACgAGQYBCAnAwMCSk0QAKAAZBgGIAcjAwI=",
  },
  {
    key: "./Runewords/Weapon/Bows/Faith (HB).d2i",
    value:
      "Sk0QCIAEZAAAasN2B0JXISN07RAgKAAU4cGDJaP/ETBiPBGUImhFUIugO0D/6JKetykAxX9KTRAAoABkGAAgJ3MDAkpNEACgAGQYAiA3EwMCSk0QAKAAZBgEICcDAwJKTRAAoABkGAYgByMDAg==",
  },
  {
    key: "./Runewords/Weapon/Bows/Harmony (GMB).d2i",
    value:
      "Sk0QCIAEZACAGtY2BsJ7F3BF7ZAlKAAU4cGDJSNeAAD6H2HixA0UMG5AybhBsXEDyiiLhQFhXJqjmFFfZGT8B0pNEACgAGQYACAHMwMCSk0QAKAAZBgCIAdjAwJKTRAAoABkGAQgFyMDAkpNEACgAGQYBiAXgwMC",
  },
  {
    key: "./Runewords/Weapon/Bows/Harmony (HB).d2i",
    value:
      "Sk0QCIAEZAAEasN2B0L9DPsH7ZAlKAAU4cGDJaP/ESZO3EAB4waUjBsUGzegorJYGBDGpTmKGfVFRsZ/Sk0QAKAAZBgAIAczAwJKTRAAoABkGAIgB2MDAkpNEACgAGQYBCAXIwMCSk0QAKAAZBgGIBeDAwI=",
  },
  {
    key: "./Runewords/Weapon/Bows/Ice (GMB).d2i",
    value:
      "Sk0QCIAEZACEGtY2BkKKRf4D7ZAqKAAU4cGDJSNeAAD6H0GatEtypDGLhcwxdAfyu2wplKcU/wFKTRAAoABkGAAgFxMDAkpNEACgAGQYAiAXMwMCSk0QAKAAZBgEIDcTAwJKTRAAoABkGAYgJ4MDAg==",
  },
  {
    key: "./Runewords/Weapon/Bows/Ice (HB).d2i",
    value:
      "Sk0QCIAEZACAasN2B0KzxPpE7ZAqKAAU4cGDJaP/EaRJuyRHGrNYyBxDdyC/y5ZCeUrxH0pNEACgAGQYACAXEwMCSk0QAKAAZBgCIBczAwJKTRAAoABkGAQgNxMDAkpNEACgAGQYBiAngwMC",
  },
  {
    key: "./Runewords/Weapon/Bows/Wrath (GMB).d2i",
    value:
      "Sk0QCIAEZAAAGtY2BsJBuMBq7ZBgKAAU4cGDJSNeAAD6LyOFh0YVnjxA9ZjM1JgiRcFYcIXnP0pNEACgAGQYACAnEwMCSk0QAKAAZBgCIBdzAwJKTRAAoABkGAQgNwMDAkpNEACgAGQYBiAnMwMC",
  },
  {
    key: "./Runewords/Weapon/Bows/Wrath (HB).d2i",
    value:
      "Sk0QCIAEZAAIasN2B8LrngYd7ZBgKAAU4cGDJaP/MlJ4aFThyQNUT8tMjSlSFIwFV3j+A0pNEACgAGQYACAnEwMCSk0QAKAAZBgCIBdzAwJKTRAAoABkGAQgNwMDAkpNEACgAGQYBiAnMwMC",
  },
  {
    key: "./Runewords/Weapon/Flail/Call to Arms (Flail).d2i",
    value:
      "Sk0QCIAEZGQXYMYWBtL04tdW7ZATKB4eKkKAAGEqEWE2Df8jvHunRO3CCyOJCFNJCLNp+JP/Sk0QAKAAZBgAIBcTAwJKTRAAoABkGAIgB4MDAkpNEACgAGQYBCAnMwMCSk0QAKAAZBgGICdDAwJKTRAAoABkGAggJ3MDAg==",
  },
  {
    key: "./Runewords/Weapon/Flail/Heart of the Oak (Flail).d2i",
    value:
      "Sk0QCIAEZACgasYWBkIdyIZ97ZAmKB4e6P8JrRRaK7RaaCmRm2RpeH/GzOmGh4cZIU5Gxn9KTRAAoABkGAAgF4MDAkpNEACgAGQYAiAnYwMCSk0QAKAAZBgEICcTAwJKTRAAoABkGAYgFwMDAg==",
  },
  {
    key: "./Runewords/Weapon/Swords/Death (PB).d2i",
    value:
      "Sk0QCIAEZAAEcjMmB1Jk7IhE7RAXKAAV4cGDJaP/EQIHRiTDdJh0Q6YYWwOZmVXFw4M+4j9KTRAAoABkGAAgF1MDAkpNEACgAGQYAiAHEwMCSk0QAKAAZBgEICdjAwJKTRAAoABkGAYgB5MDAkpNEACgAGQYCCAnUwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Destruction (PB).d2i",
    value:
      "Sk0QCIAEZACIejMmB1KwRTcB7ZAZKAAV4cGDJaP/Ebx6pUFGq05gmAXDo1iLA9nYVU7BGEPP5T9KTRAAoABkGAAgJ2MDAkpNEACgAGQYAiAngwMCSk0QAKAAZBgEIDcDAwJKTRAAoABkGAYgNxMDAkpNEACgAGQYCCAXgwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Fortitude(PB).d2i",
    value:
      "Sk0QCIAEZAAAcjMmB0LcoA0k7ZAhKAAU4cGDJaP/EJBFYMnyBFQKqBVQLaDStOQwyR4eKNiY/0pNEACgAGQYACAHEwMCSk0QAKAAZBgCIBcjAwJKTRAAoABkGAQgF0MDAkpNEACgAGQYBiAngwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Grief (PB).d2i",
    value:
      "Sk0QCIAEZAAAcjMmB9LZEEVl7ZAkKAAV4cGDJaP/Vh5deG9Iz2nssWg074Ga8R9KTRAAoABkGAAgB1MDAkpNEACgAGQYAiAHMwMCSk0QAKAAZBgEICeDAwJKTRAAoABkGAYgJzMDAkpNEACgAGQYCCAHgwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Last Wish (PB).d2i",
    value:
      "Sk0QCIAEZAAIejMmB+KWe69v7ZAvKAAW4cGDJaP/Ee7eRSS7JCYOo0ygGJOkUCRbFjLAI/4DSk0QAKAAZBgAIDcTAwJKTRAAoABkGAIgJzMDAkpNEACgAGQYBCA3EwMCSk0QAKAAZBgGICeTAwJKTRAAoABkGAggNxMDAkpNEACgAGQYCiA3AwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Lawbringer (PB).d2i",
    value: "Sk0QCIAEZAAAcjMmB7KSZOxG7ZAwKAAT4cGDJaP/IPTBsJRmQ5AWLZt0ZJfuSGPPFZT/Sk0QAKAAZBgAIBcTAwJKTRAAoABkGAIgJwMDAkpNEACgAGQYBCAXgwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Oath (PB).d2i",
    value:
      "Sk0QCIAEZAAIcjMmB8LlUM4B7RA6KAAU4cGDJaP/EahS7SKb9MDUGNWFh1mkhYMDM4gdCor/Sk0QAKAAZBgAIBczAwJKTRAAoABkGAIgJxMDAkpNEACgAGQYBCAnMwMCSk0QAKAAZBgGIBdzAwI=",
  },
  {
    key: "./Runewords/Weapon/Swords/Phoenix (PB).d2i",
    value:
      "Sk0QCIAEZAAIcjMmB0IPWocD7RBAKAAU4cGDJaP/ESBDBgH5UeUSn2bMCgd1DHWB3JTjP0pNEACgAGQYACAnYwMCSk0QAKAAZBgCICdjAwJKTRAAoABkGAQgJ4MDAkpNEACgAGQYBiA3EwMC",
  },
  {
    key: "./Runewords/Weapon/Swords/Spirit (PB).d2i",
    value:
      "Sk0QCIAEZACkejMmB0K57A907ZBNKAAU4cGDJaP/A2wJIEHoG7NMc/ujSYj/Sk0QAKAAZBgAIAdzAwJKTRAAoABkGAIgFwMDAkpNEACgAGQYBCAHkwMCSk0QAKAAZBgGIBcTAwI=",
  },
  {
    key: "./Runewords/Weapon/Swords/Voice of Reason (PB).d2i",
    value:
      "Sk0QCIAEZAAIcjMmB0Jrq4817RA+KAAU4cGDJaP/Nsi47eaRq6depsaoFiTGGiAeTzH+A0pNEACgAGQYACAnAwMCSk0QAKAAZBgCIBeDAwJKTRAAoABkGAQgBxMDAkpNEACgAGQYBiAHIwMC",
  },
  { key: "./Sets/Aldur's Watchtower/Armor.d2i", value: "Sk0QCIAAZQAAUlfHBgJ5WxSscTEEbmRkJA4AGgGvDzZJQbZFhlcKQHipAOT/gNf/Aa//A17/AQ==" },
  { key: "./Sets/Aldur's Watchtower/Boots.d2i", value: "Sk0QAIAAZQAEgkcnBoLkO9O7cVEEciAh4RyQsoCaA8gJMjA8OQqm/wW8/gt4/Rfw+g8=" },
  { key: "./Sets/Aldur's Watchtower/Helmet.d2i", value: "Sk0QCIAAZQBEQiaHA4KRHPrccSEEtkBBQc6GiA9kWEGWJce0/gd4/Q/w+h/g9R8=" },
  { key: "./Sets/Aldur's Watchtower/Weapon.d2i", value: "Sk0QCIAAZQAIktNGB4LbeSCvcUEEkJDMqYBa8MmQl+Ch8FHoIsvD7T+Al/8AXv4DePkP" },
  { key: "./Sets/Angelic Raiment/Amulet.d2i", value: "Sk0QAIAAZAAGEtZWB4IjU8u5boUaMLKcHOr/gTX//+Q/" },
  { key: "./Sets/Angelic Raiment/Armor.d2i", value: "Sk0QCIAAZAAgIud2BgILOa3oRTEDdqChIQYEFCKG/x9A8f8E2X8=" },
  { key: "./Sets/Angelic Raiment/Ring.d2i", value: "Sk0QAIAAZQAAIpfmBoIGhQDQaw0aMA7QUEL+B4f9h2L5Hw==" },
  { key: "./Sets/Angelic Raiment/Weapon.d2i", value: "Sk0QCIAAZQAEMicmBwLfYrUYVCEDQEDEmLCEHof/IyxZ8r+L7D8=" },
  { key: "./Sets/Arcanna's Tricks/Amulet.d2i", value: "Sk0QIIAAZABkEtZWB4K6eMBnbQUdMBK8bKD4D8Xy/wmj/w==" },
  { key: "./Sets/Arcanna's Tricks/Armor.d2i", value: "Sk0QCIAAZAAEwkYHB4IxhYuNbtED6sDDI4aIIYv9/+CG/wFU/wE=" },
  { key: "./Sets/Arcanna's Tricks/Helmet.d2i", value: "Sk0QKIAAZAAIMrcGBwJ62RkbbcEDKiAhIYYS0YngvzXsf4qg/w==" },
  { key: "./Sets/Arcanna's Tricks/Weapon.d2i", value: "Sk0QCIAAZAAAcjdHBwKdIvcabbEDZGTEmJI0yvxPIPV/Q8F/" },
  { key: "./Sets/Artic Gear/Armor.d2i", value: "Sk0QCIAAZAAgEleXBoK9maCIQnEDLEBBIQaEoid4UvCs4GnB898a9n9F0H8=" },
  { key: "./Sets/Artic Gear/Belt.d2i", value: "Sk0QAIAAZAAAYifGBoJ8wFgwbYEDGuDgYHxAwQqt/1AY/6/g+Q8=" },
  { key: "./Sets/Artic Gear/Gloves.d2i", value: "Sk0QAIAAZAAIQnfGBgIJcmJhbZEDKiAhYRyg0cXzf4IM/wWo/gM=" },
  { key: "./Sets/Artic Gear/Weapon.d2i", value: "Sk0QCIAAZAAEMncnBgIozkJqbWEDYGDEiCBDxh0U/8FB/21QeFj6Dw==" },
  { key: "./Sets/Beserker's Arsenal/Armor.d2i", value: "Sk0QCIAAZAAEMgfHBoLJB1gUbdEC0uDhIcIIYQrz3xr2Hw==" },
  { key: "./Sets/Beserker's Arsenal/Helmet.d2i", value: "Sk0QCIAAZAAIgsbWBgJXaStFW8ECOICBIcKHDJxY+g8O+g8=" },
  { key: "./Sets/Beserker's Arsenal/Weapon.d2i", value: "Sk0QCIAAZAAAIhOGB4JgyAcAbuECMDBE8FG4I+N/BBky/gM=" },
  { key: "./Sets/Bul Kathos' Children/Colossus Blade.d2i", value: "Sk0QCIAAZAAAcnNGBgJY5D02bTEHZGQEiIAM2QmjFEYrjFoYRQl0QSEa/Qc=" },
  {
    key: "./Sets/Bul Kathos' Children/Mythical Sword.d2i",
    value: "Sk0QCIAAZAAEcnNHBhLxI7URbUEHWFgEAEATARmyE2Q5/vlHRhfUf0pNEACgAAAYACA3EwMC",
  },
  { key: "./Sets/Cathan's Traps/Amulet.d2i", value: "Sk0QAIAAZABiEtZWB4JJHmPTTAUOMMZ4AJX/E2T4D6XvPw==" },
  { key: "./Sets/Cathan's Traps/Armor.d2i", value: "Sk0QCIAAZQAAMobmBoLsIwXjaqEBqtDSIsaHDGyR+e+k8P8E1H8=" },
  { key: "./Sets/Cathan's Traps/Helmet.d2i", value: "Sk0QCIAAZAAE0ja3BgIHWwMxVLEBSkBBIUICmhVL/61B/wE=" },
  { key: "./Sets/Cathan's Traps/Ring.d2i", value: "Sk0QAIAAZQBgIpfmBgJjmCfba5UOEEQIPAz/Aaj8Bw==" },
  { key: "./Sets/Cathan's Traps/Weapon.d2i", value: "Sk0QKIAAZAAIIjZHB4KjYuUkbZEBUFDE8JPEUPA/gdT/EzwpeFbwtOD5Dw==" },
  { key: "./Sets/Civerb's Vestments/Amulet.d2i", value: "Sk0QAIAAZAACEtZWB4J6IJwkbYUAMDagKBH/r1j6/2EE/wE=" },
  { key: "./Sets/Civerb's Vestments/Shield.d2i", value: "Sk0QCIAAZAAiwiZ3BoIPW5tTbQEAMICBIQaF50MG/iew+d+C6T8=" },
  { key: "./Sets/Civerb's Vestments/Weapon.d2i", value: "Sk0QCIAAZAAAcjY3BoJq25NvSyEAeHhEmLCEhct/bch/" },
  { key: "./Sets/Cleglaw's Brace/Gloves.d2i", value: "Sk0QAIAAZAAA0nbGBoJe0GfEb4EAJgABIUQJWMr8B0f9Bw==" },
  { key: "./Sets/Cleglaw's Brace/Shield.d2i", value: "Sk0QKIAAZAAIMtfGBoIOxe4bbXEAKAABIcKHDbj5+n8iKEXQiqAWQf8B" },
  { key: "./Sets/Cleglaw's Brace/Weapon.d2i", value: "Sk0QCIAAZQAEwjZHBoJxvZLSamEAWFhEuCOjkey/NuU/" },
  { key: "./Sets/Cow King's Leathers/Armor.d2i", value: "Sk0ACIAAZAAAMkdXBwLnEJ6/QGEHWgACIgYEHieIUhCtIGpBZKyoQfL/gI//yQoJav8B" },
  { key: "./Sets/Cow King's Leathers/Boots.d2i", value: "Sk0AAIAAZAAEYidGB4Irb7MfbXEHHuDgAAigfWgBjIwRUPrAyP4D" },
  { key: "./Sets/Cow King's Leathers/Helmet.d2i", value: "Sk0ACIAAZAAIghcGB4INFve/QFEHfsDAIMaHKtj5X87434niPw==" },
  { key: "./Sets/Death's Disguise/Belt.d2i", value: "Sk0QIIAAZAACwibGBgLfvOodbQEDGMDAIHzwQKb/TwSlCFoR1CLoPw==" },
  { key: "./Sets/Death's Disguise/Gloves.d2i", value: "Sk0QIIAAZAAiwnbGBoJ8GlMObfECGsDAILQgc/P1v4vsPw==" },
  { key: "./Sets/Death's Disguise/Weapon.d2i", value: "Sk0QCIAAZQAAcjdHBoJhbXsnXxEDWFhEiJAhAw/CfxsZS5b+Aw==" },
  { key: "./Sets/Griswold's Legacy/Armor.d2i", value: "Sk0QCIAAZQAAghcmBwLXAkuucSEFmMPDYwAAmg/+2cLDSwNA/wE=" },
  { key: "./Sets/Griswold's Legacy/Helmet.d2i", value: "Sk0QCIAAZQAEUifnBgJshv/jcREFYCEjQwKEJSduUtysuGlxA0VwC4864T+vDAD9Bw==" },
  { key: "./Sets/Griswold's Legacy/Shield.d2i", value: "Sk0QCIAAZQAIAhdmBoLXrRGicUEF1qGlZQAF6oMdTnyl+Frx1eLLTPU/" },
  { key: "./Sets/Griswold's Legacy/Weapon.d2i", value: "Sk0QCIAAZYQIcHM3B4JkJoaKcTEFjIzQiQAP3haoLjw93P7zwgDQ/wqKBcr/CooFyn8=" },
  { key: "./Sets/Heaven's Brethren/Armor.d2i", value: "Sk0QCIAAZQACgic3BwLisP7ncWEGqCEjI8CBNR/8A2JECJQtUP8B" },
  { key: "./Sets/Heaven's Brethren/Helmet.d2i", value: "Sk0QCIAAZAAKUofWBgIqFl83T3EGUoGCIgAAFQGvDzzYwjOGZWxAQvEf" },
  { key: "./Sets/Heaven's Brethren/Shield.d2i", value: "Sk0QCIAAZAAGUkc3B4IrmlUHTFEGaAEQIAEhhewDD1JAOfGYkf0H" },
  { key: "./Sets/Heaven's Brethren/Weapon.d2i", value: "Sk0QCIAAZAAActMWBoLuOsQdTEEGeHgEgEHhoQvP2MCCQhvzHw==" },
  { key: "./Sets/Hsaru's Defence/Belt.d2i", value: "Sk0QAIAAZAAI0ibGBgJP6spUbVEAHgABIRygscLovzXqPw==" },
  { key: "./Sets/Hsaru's Defence/Boots.d2i", value: "Sk0QAIAAZAAE0iZGB4JTax5vbTEAJgABIZxYAoP6D476Dw==" },
  { key: "./Sets/Hsaru's Defence/Shield.d2i", value: "Sk0QAIAAZAAAIlY3BgKlMWdPbUEAIMDAIABQESH8t0b9Bw==" },
  { key: "./Sets/Hwanin's Majesty/Armor.d2i", value: "Sk0QCIAAZAAEgjfGBgL8i2clbdEGkEFCIsABQh+k0aIp2aCC4j8=" },
  { key: "./Sets/Hwanin's Majesty/Belt.d2i", value: "Sk0QAIAAZAAk0ibGBoJIG5ghbeEGHgABAcgYQpDD1AlYY/4D" },
  { key: "./Sets/Hwanin's Majesty/Helmet.d2i", value: "Sk0QCIAAZAAMgifnBgJf9TQ0bcEG+CAjIwAEMiOUFVdK5P8=" },
  { key: "./Sets/Hwanin's Majesty/Weapon.d2i", value: "Sk0QCIAAZAAAkmP3BoK6Jm0HbfEGAAJEQIZsglIyigy68IwNLSj+Aw==" },
  { key: "./Sets/Immortal King/Armor.d2i", value: "Sk0QCIAAZQAoUhcmBwInwgYYY3EExMTDI/4HzbQg4wUCoGQFDYX/Y1r/V2j9P6H1P4XWfwgy/gM=" },
  { key: "./Sets/Immortal King/Belt.d2i", value: "Sk0QAIAAZQAEoocmBgLZ6iptY4EEfICB4QPI+eCCE04pov5/mMP/Ma3/EMj8J0Hxn1cIgP4D" },
  { key: "./Sets/Immortal King/Boots.d2i", value: "Sk0QAIAAZQAkgocmBgJloFGnYaEEfoCB4R1gMsGND1UAw/sPpe8/LxAA/f+giv92/gc=" },
  { key: "./Sets/Immortal King/Gloves.d2i", value: "Sk0QAIAAZQAIgod2BoJQmJH5YZEEfoCB4QOgEUD7sIRkhAmM/11a/z8I4j8PxX8fiv+GxH8=" },
  { key: "./Sets/Immortal King/Helmet.d2i", value: "Sk0QCIAAZQBIIhZWAwKcw9EkY2EEeHBzQ8CHQzxJBIUxC/ISAdB/" },
  { key: "./Sets/Immortal King/Weapon.d2i", value: "Sk0QCIAAZQAMctN2A4JkiOz1YbEEeHjIj4AMWRdeHm56uCFCYfofxnTj/zKO7v7b+GNr+T9HV11Z+k9DP+1/" },
  { key: "./Sets/Infernal Tools/Belt.d2i", value: "Sk0QAIAAZAAEQifGBgKoislnbbECICAhYRyg8WEE/1ss/bfzPw==" },
  { key: "./Sets/Infernal Tools/Helmet.d2i", value: "Sk0QCIAAZAAAMhYGBwK4Lhb7UJECHsDAIMIJnhQ8K3ha8Mih/luD/gM=" },
  { key: "./Sets/Infernal Tools/Weapon.d2i", value: "Sk0QCIAAZAAIcnbnBgITjMHNU6ECHh5EqIBMUf6Do/4D" },
  { key: "./Sets/Iratha's Finery/Amulet.d2i", value: "Sk0QIIAAZAAkEtZWBwKtAFNUbYUEEFpAufn6fyIoRdCKoBZB/wE=" },
  { key: "./Sets/Iratha's Finery/Belt.d2i", value: "Sk0QAIAAZAAEQifGBgJjfK3Tb8EAICDRIFQoLhQfRvBfgOo/" },
  { key: "./Sets/Iratha's Finery/Gloves.d2i", value: "Sk0QIIAAZAAIQnfGBgKQagE/baEAKiAhIayAsvN/F9R/" },
  { key: "./Sets/Iratha's Finery/Helmet.d2i", value: "Sk0QCIAAZQAAMibnBgJQX/jocbEAbiAjI8IJqBRQ/61B/wE=" },
  { key: "./Sets/Isenhart's Armory/Armor.d2i", value: "Sk0QCIAAZQAAIiY3BwJmW9XWcfEAnCAjI8IHGYwQ/luD/gM=" },
  { key: "./Sets/Isenhart's Armory/Helmet.d2i", value: "Sk0QKIAAZAAMYobGBgK3dKBUbQEBSODhIYIAkwjh/wmdFDordFro/Ac=" },
  { key: "./Sets/Isenhart's Armory/Shield.d2i", value: "Sk0QKIAAZAAIckY3B4J9CBIUbeEAWoCCIsIHGQAi/0/opNBZodNC5z8=" },
  { key: "./Sets/Isenhart's Armory/Weapon.d2i", value: "Sk0QCIAAZQAEIjZHBgJqKOkXatEAQEBEqKB0Qf0Hp/wH" },
  { key: "./Sets/M'avina's Battle Hymn/Armor.d2i", value: "Sk0QCIAAZQAsUsdGBgLXLXvOcbEFKgQDI8QHtIxgthjxCgBQsuEGhTXw/xjZfw==" },
  { key: "./Sets/M'avina's Battle Hymn/Belt.d2i", value: "Sk0QAIAAZQAEomcnBgLswC/McdEFXODggHzggY9ClgSD+n9iKcXSiqUWS/8B" },
  { key: "./Sets/M'avina's Battle Hymn/Gloves.d2i", value: "Sk0QAIAAZQAkgkd3BoJMihmHccEFciAhgQFQEfD6wAMbBhIsn3Cy87+NQX5k/5ca+Q8=" },
  { key: "./Sets/M'avina's Battle Hymn/Helmet.d2i", value: "Sk0QCIAAZQAQMpY2A4LoO83vcaEFjEBBIU6CnA+gUIJ2kf3/k/93jPw/sZRiacVSi6X/" },
  { key: "./Sets/M'avina's Battle Hymn/Weapon.d2i", value: "Sk0QCIAAZQAAGtY2BgIHfFa8ceEFbm7EicCL1wQZuvA6Bf7TkMv739gDg+I/LwAA/Qc=" },
  { key: "./Sets/Milabrega's Regalia/Armor.d2i", value: "Sk0QCIAAZAAIEhYmBwJq/cHFb4EB5sHDI4IIwcngPwQy/wE=" },
  { key: "./Sets/Milabrega's Regalia/Helmet.d2i", value: "Sk0QCIAAZQAAMibnBgIukwncY3EBbiAjI8KBFwle/q/Q+g8=" },
  { key: "./Sets/Milabrega's Regalia/Shield.d2i", value: "Sk0QCIAAZQAEspZGBwJFrS72TVEBOODhIcaHEUDB+39Ayn8IMv4D" },
  { key: "./Sets/Milabrega's Regalia/Weapon.d2i", value: "Sk0QCIAAZQAMcjcHBwJk8b2za2EBjIwEiCBDxpQli/0H" },
  { key: "./Sets/Naj's Ancient Vestige/Armor.d2i", value: "Sk0QCIAAZAAEUsdGBwK1CO4/bZEHOMTDI8CBMB9scmIpxdKKpRZLW1DktH/yHw==" },
  { key: "./Sets/Naj's Ancient Vestige/Circlet.d2i", value: "Sk0QCIAAZAAAMpYGA4LxJ6gCbaEHUDAyIgCAlw9VgJExIksmK2pg/Ac=" },
  { key: "./Sets/Naj's Ancient Vestige/Staff.d2i", value: "Sk0QCIAAZAAIYjM2BwL26BIybYEHRkYECDBMYBbBkiUZRgtpZH/CbLGhqOg/" },
  { key: "./Sets/Natalya's Odium/Armor.d2i", value: "Sk0QCIAAZQAAUjfGBgI4TkGzQAEE9ENCYsCHdbRYcvPFKwZA2JD/" },
  { key: "./Sets/Natalya's Odium/Boots.d2i", value: "Sk0QAIAAZQAEgtcmBgJ2nT7NQBEEbAAhBHw4RIqlFUtJZMDw4gn/AQ==" },
  { key: "./Sets/Natalya's Odium/Helmet.d2i", value: "Sk0QCIAAZQAEioeWAwKsfcqLQOEDDoGCIgAAGgG+DzcZMZwwSmG0wqiF0X8=" },
  { key: "./Sets/Natalya's Odium/Weapon.d2i", value: "Sk0QCIAAZQAIehMnBwJyZLKOQPEDiIgEiIAMGQyGCDZkZJB14c2Zh5sebv8B" },
  { key: "./Sets/Orphan's Call/Belt.d2i", value: "Sk0QAIAAZAAMokcnBoLUfHYqTJEGaiAhAUBYsoKHR8FH4T8=" },
  { key: "./Sets/Orphan's Call/Goves.d2i", value: "Sk0QAIAAZAAEgmd3BoKIpCIPTKEGZODgAECQMYGME0FZrgvqPw==" },
  { key: "./Sets/Orphan's Call/Helmet.d2i", value: "Sk0QCIAAZAAAgofWBoI0ev4RTIEG2oCCIgCAFwh4xsgQjRo9/gM=" },
  { key: "./Sets/Orphan's Call/Shield.d2i", value: "Sk0QCIAAZAAIgtfGBoKyubQtTLEGhAAEJACEVxTuLGmGZ+d/" },
  { key: "./Sets/Sander's Folly/Boots.d2i", value: "Sk0QAIAAZAAEYidGB4LEOZ8absEHIODgAAAoEaCaQAYY3n8=" },
  { key: "./Sets/Sander's Folly/Gloves.d2i", value: "Sk0QAIAAZAAKYnfGBoKj51cKbtEHIODgABxA8mEEOTwgYUkX1H8=" },
  { key: "./Sets/Sander's Folly/Helmet.d2i", value: "Sk0QAIAAZABAMhYGB4JPvTMNbrEHGsCwADhBQDm0hvwH" },
  { key: "./Sets/Sander's Folly/Weapon.d2i", value: "Sk0QCIAAZAAIInbnBoIYZMMXbuEHHh4ESJATYckSGxlLZHwg0qD+Aw==" },
  { key: "./Sets/Sazabi's Grand Tribute/Armor.d2i", value: "Sk0QCIAAZAAEUgfHBoLD57cObREHHuThIQCAnANrPmhmjGwPa/8B" },
  { key: "./Sets/Sazabi's Grand Tribute/Helmet.d2i", value: "Sk0QCIAAZAAIgofGBgKivu40bSEHvODhIcAHN5wwSmH0J/8B" },
  { key: "./Sets/Sazabi's Grand Tribute/Weapon.d2i", value: "Sk0QCIAAZAAAcsM2BwJOlMo3bQEHAAIAKBHwimDJko2METJdeHmk/gc=" },
  { key: "./Sets/Sigon's Complete Steel/Armor.d2i", value: "Sk0QCIAAZAAMckaHBoLrx2wXWFECInFzIwKEDCmg/juh/Ac=" },
  { key: "./Sets/Sigon's Complete Steel/Belt.d2i", value: "Sk0QAIAAZQBQgibGBgLoV5nSZXECKoCBIRygccLovzXoPw==" },
  { key: "./Sets/Sigon's Complete Steel/Boots.d2i", value: "Sk0QAIAAZQAIgiZGBwJYDjwlXmECMoCBYazQAoP6P0GG/1As/wM=" },
  { key: "./Sets/Sigon's Complete Steel/Gloves.d2i", value: "Sk0QAIAAZQAAgnbGBgJNt3TtazECMoCBIQBQmUDB/y6y/w==" },
  { key: "./Sets/Sigon's Complete Steel/Helmet.d2i", value: "Sk0QCIAAZAAQcobWBoIItBVETUECWoCCIkICnw8j+A8O+g8=" },
  { key: "./Sets/Sigon's Complete Steel/Shield.d2i", value: "Sk0QCIAAZAAEQvd2B4KyJPzwboECRsDDIwAF6k/+Aw==" },
  { key: "./Sets/Tal Rasha's Wrappings/Amulet.d2i", value: "Sk0QAIAAZUQEENZWB4KDQ5GScZUmQA5ISaCUYkrGAMKU6H8az38=" },
  { key: "./Sets/Tal Rasha's Wrappings/Armor.d2i", value: "Sk0QCIAAZQAgUkeHBgLJQM7ccfEETnRzI8IHzYx4Tmil0FqhBYV3C8r/NJ7/" },
  { key: "./Sets/Tal Rasha's Wrappings/Belt.d2i", value: "Sk0QAIAAZQAAotcmBoKqkQG1ccEEZAABYQigJfCBMrcFSk75/4MR/qfx/Ac=" },
  { key: "./Sets/Tal Rasha's Wrappings/Helmet.d2i", value: "Sk0QCIAAZQCAije3BgJ3TSihcQEFwEBBIcABLgl8PtzgRFCKoBVBLYJ4KHwo/gM=" },
  { key: "./Sets/Tal Rasha's Wrappings/Weapon.d2i", value: "Sk0QCIAAZQBE+iYWBgI+YBz3ceEEZGTEC6A6kCVBWxrUmh5a80Nrguj/lOR/04f/Th/+Lw3yHw==" },
  { key: "./Sets/Tancred's Battlegear/Amulet.d2i", value: "Sk0QAIAAZAAMEtZWBwLOaUTub4UQMEQII4L/UGT/T+DhPw==" },
  { key: "./Sets/Tancred's Battlegear/Armor.d2i", value: "Sk0QCIAAZAAIYlbHBoKwSK4GbfEBVmFkJAKAlwNI/luD/gM=" },
  { key: "./Sets/Tancred's Battlegear/Boots.d2i", value: "Sk0QAIAAZAAEwiZGB4L7GWC5TwECGsDAYAhQccj4D0b2H4DKfw==" },
  { key: "./Sets/Tancred's Battlegear/Helmet.d2i", value: "Sk0QKIAAZAAOIobWBgKaitRKbSECXICCIkIEBQomoPD/BE8KnhU8LXj+Aw==" },
  { key: "./Sets/Tancred's Battlegear/Weapon.d2i", value: "Sk0QCIAAZAAA0gaXBgItp0L3WeEBNDTEiAAFyoQl/ieg+d8F9R8=" },
  { key: "./Sets/The Disciple/Amulet.d2i", value: "Sk0QAIAAZAAMEtZWB4LBZTUrbZUvAFYQtSBzoviT/w==" },
  { key: "./Sets/The Disciple/Armor.d2i", value: "Sk0QCIAAZAAIUleXBgLBFtY4bSEGukNBIcCH1JxQytHHKzKSDTBk/gM=" },
  { key: "./Sets/The Disciple/Belt.d2i", value: "Sk0QAIAAZAAAUtc2BgLrK2gXbTEGlgABAQBQEaD6wIMTQSmCVgS1CPoP" },
  { key: "./Sets/The Disciple/Boots.d2i", value: "Sk0QAIAAZQAEgscmBgLPLixLXREGWsDAACzI+TACMDI7/wM=" },
  { key: "./Sets/The Disciple/Gloves.d2i", value: "Sk0QAIAAZAAgUsd2BoJnDjiDbgEGkMDAAHwYwQmyLqg8co0NZSj+Aw==" },
  { key: "./Sets/Trang-Oul's Avatar/Armor.d2i", value: "Sk0QCIAAZQBmilfHBoKlMJ69cWEFwmJkJBQESyDItNDawgOGx0sCQP9TkP0nkfEf" },
  { key: "./Sets/Trang-Oul's Avatar/Belt.d2i", value: "Sk0QAIAAZQAAWkc3BgJs5L/lcZEFmCAhQRwQk0Bqgc8HNygZt/Bk+n+F1n8=" },
  { key: "./Sets/Trang-Oul's Avatar/Gloves.d2i", value: "Sk0QAIAAZQAgitd2BoKWRrCXcYEFbAABAXxAwQqoNCheEABiuuQ/" },
  { key: "./Sets/Trang-Oul's Avatar/Helmet.d2i", value: "Sk0QCIAAZQDAWoeWAwK9F7uQcVEFToGCIkAC2w9uUDI6oYxp/Qc=" },
  { key: "./Sets/Trang-Oul's Avatar/Shield.d2i", value: "Sk0QCIAAZQDE6laWAwJlFJaKcXEFlEBBIQyAHAEvCt6HQ5z4aqHFKwJA/6Fm/FfS/gc=" },
  { key: "./Sets/Vidala's Rig/Amulet.d2i", value: "Sk0QAIAAZAAIEtZWB4Jv4OzqbhUKEA68WGH0H4rlfw==" },
  { key: "./Sets/Vidala's Rig/Armor.d2i", value: "Sk0QCIAAZAAAwlYWBoIRPvCBTzEBNoCBIYaA1Qce/D+h9N8a9R8=" },
  { key: "./Sets/Vidala's Rig/Boots.d2i", value: "Sk0QIIAAZAAKQidGB4JlbvdybSEBKiAhISywBSP7f0Inhc4KnRY6/wE=" },
  { key: "./Sets/Vidala's Rig/Weapon.d2i", value: "Sk0QCIAAZAAEwiYmBgKdujpKbhEBWFhEkBFQ8B8c9B8=" },
  { key: "./Uniques/Amulets/Atma's Scarab.d2i", value: "Sk0QAIAAZQAwEtZWBwLO/Y8z8YWI0KIvhxlmkHFSyHJ3UBgThCj8Bw==" },
  { key: "./Uniques/Amulets/Crescent Moon.d2i", value: "Sk0QAIAAZQAQEtZWB4I54nzO742HkKBphMLD4OORReQo/wE=" },
  { key: "./Uniques/Amulets/Highlord's Wrath.d2i", value: "Sk0QAIAAZQAmGtZWB4KnIFr08QWKkKJKRuBBF9SfAHr6hv8=" },
  { key: "./Uniques/Amulets/Mara's Kaleidoscope.d2i", value: "Sk0QAIAAZUQEENZWB4IIcHjv8QWIAKAkQElAaUDpBFQKqBVQLaD+6D8=" },
  { key: "./Uniques/Amulets/Metalgrid.d2i", value: "Sk0QAIAAZQAGGtZWB4LfoRr08Y27MEG4D2g5UZWiakVViypmDBMUFMwsLRYW/gM=" },
  { key: "./Uniques/Amulets/Nokozan Relic.d2i", value: "Sk0QAIAAZQASEtZWB4LLFfDx8JU6cIIMhYIxYCDLjUH9Bw==" },
  { key: "./Uniques/Amulets/Saracen's Chance.d2i", value: "Sk0QAIAAZQBAEtZWBwJHctc/8ZWKAIAlAEsAawDrxFKKpRVLLZaSCUwo/gM=" },
  { key: "./Uniques/Amulets/Seraph's Hymn.d2i", value: "Sk0QAIAAZQBmGtZWBwLZNATJ8QWXkMXyGNFjZI9efPT6I14aAPoP" },
  { key: "./Uniques/Amulets/The Cat's Eye.d2i", value: "Sk0QAIAAZQBSEtZWB4JrPmyR8JWGICD3wQ0gyHRBgZH9Bw==" },
  { key: "./Uniques/Amulets/The Eye of Etlich.d2i", value: "Sk0QAIAAZQAyEtZWB4KdU/3H8A07AAKFDYECUDwOWfJPDKn/" },
  { key: "./Uniques/Amulets/The Mahim-Oak Curio.d2i", value: "Sk0QAIAAZQBGGtZWB4JT8D848IU7AEAlgEqAaoAKgoIPFDjBk4JnBU8Lnjse/gM=" },
  { key: "./Uniques/Amulets/The Rising Sun.d2i", value: "Sk0QAIAAZQByEtZWB4I8QnND7xWHAAMDhhI0C/qJklE4CNYZ/wE=" },
  { key: "./Uniques/Armors/Arkain's Valor.d2i", value: "Sk0QCIAAZQAAWgfHBgJ/2yCs8bEPIOThISDQEvGMkf3RN+I/" },
  { key: "./Uniques/Armors/Atma's Wail.d2i", value: "Sk0QCIAAZQAkgkeHBgK7jTAI8cENdHJzIwS8IIBKIqMEbZJBwRsjswb9Bw==" },
  { key: "./Uniques/Armors/Black Hades.d2i", value: "Sk0QCIAAZQAIglfHBoJAZf2Z8dENwmJkZCAgyyJ25oGyR6//" },
  { key: "./Uniques/Armors/Blinkbat's Form.d2i", value: "Sk0QCIAAZQAAylYWBoLFR40o7wEFMICBIT6MAIQMGAMGwHjG8P4D" },
  { key: "./Uniques/Armors/Boneflesh.d2i", value: "Sk0QCIAAZQAAAsdGBwI900ur8YEF/sDDIyDgmTACj8KhzH8=" },
  { key: "./Uniques/Armors/Corpsemourn.d2i", value: "Sk0QCIAAZQAMghcmBwIdTAZX8OENmsPDIwCgDFBBoLWiCgYDiWQCEwZmhRIoKP8B" },
  { key: "./Uniques/Armors/Crow Caw.d2i", value: "Sk0QCIAAZQAQgjfGBgJ9GCEC8WENkkFCIgS8INDqMhozOjT6Dw==" },
  { key: "./Uniques/Armors/Darkglow.d2i", value: "Sk0QCIAAZQAIKud2BoJUhKqz8TEFdqAhISCQmUBBCJkTPChKCh4VZQUPi9KCx0XJcv8B" },
  { key: "./Uniques/Armors/Duriel's Shell (Up).d2i", value: "Sk0QCIAAZQAEWic3BwIFBf6y8YEN/iMjIwC8QEB2wiiF0QqjFkZJyLgcMrWmYEP+Aw==" },
  { key: "./Uniques/Armors/Duriel's Shell.d2i", value: "Sk0QCIAAZQAAiic3BwIFBf6y8YENqiEjIwC8QEB2wiiF0QqjFkZJyDK1pmBDVpD9Bw==" },
  { key: "./Uniques/Armors/Goldskin.d2i", value: "Sk0QCIAAZQAEYlbHBgKeRVtV8bEFWGFkJCBYOlGVompFVYsqJ4onyLLYfw==" },
  { key: "./Uniques/Armors/Greyform.d2i", value: "Sk0QCIAAZQAIEleXBoKAJVjN8fEEKkAxIQSoPnhgxHDCaIURj8J/" },
  { key: "./Uniques/Armors/Guardian Angel.d2i", value: "Sk0QCIAAZQAEisdGBwJJ6rTv8KENOsLDIyAgo0CheCoei+fiTVmyoBlZveI/" },
  { key: "./Uniques/Armors/Hawkmail.d2i", value: "Sk0QCIAAZQAMMjfGBoLqsjCR8UEFjkBCIiCQWRHE4oHxZPof" },
  { key: "./Uniques/Armors/Heavenly.d2i", value: "Sk0QCIAAZQAQwkYHB4I2KX2M8dEF7MDDIwK8IJDZkHGCJwXPCp4WPHqM8CHnPw==" },
  { key: "./Uniques/Armors/Iceblink.d2i", value: "Sk0QCIAAZQAAOgfHBoIrKMjW8XEF1ODhISBAGRGsgMqChsJ/" },
  { key: "./Uniques/Armors/Ironpelt.d2i", value: "Sk0QCIAAZQAIikdXB4IHrSkO70ENSAECIg7kgEBGBDUCStJnDfsP" },
  { key: "./Uniques/Armors/Leviathan.d2i", value: "Sk0QCIAAZQAEWsdGBoL7PJry8dETLATTIgBIQUD2ARQkMjD9Dw==" },
  { key: "./Uniques/Armors/Que-Hegan's Wisdon.d2i", value: "Sk0QCIAAZQBgikcHB4Im/BS58fENIMLDIwK8IIAaoYxBpUH9iaLBfw==" },
  { key: "./Uniques/Armors/Rattlecage.d2i", value: "Sk0QCIAAZQAEekaHBoIidoq676EFInFzIya08EEacGaIMv8B" },
  { key: "./Uniques/Armors/Rockfleece.d2i", value: "Sk0QCIAAZQAEasZGBoLJlNbz8ZEF6AADIwCUQBAkoiChsEXrPw==" },
  { key: "./Uniques/Armors/Shaftstop (Up).d2i", value: "Sk0QCIAAZQAIWofmBoK1EeeS8XENBtTSIg5wgcANhD4SHlwO/wE=" },
  { key: "./Uniques/Armors/Shaftstop.d2i", value: "Sk0QCIAAZQBkiofmBoK1EeeS8XENwNHSIg5wgcANhD4SHv8B" },
  { key: "./Uniques/Armors/Skin of the Flayerd One.d2i", value: "Sk0QCIAAZQBoiscWBgLcQ8367zENJsHBISD44nFI4qHkdvLgp/wH" },
  { key: "./Uniques/Armors/Skin of the Vipermagi (Up).d2i", value: "Sk0QCIAAZQBkWlcWBoLD9eEi7yENwIOBISDgGdGcqEpRtaKqRRWXQxrZn/wH" },
  { key: "./Uniques/Armors/Skin of the Vipermagi.d2i", value: "Sk0QCIAAZQAAglcWBoLD9eEi7yENEoGBISDgGdGcqEpRtaKqRVUa2Z/8Bw==" },
  { key: "./Uniques/Armors/Skullder's Ire (Up, Eth).d2i", value: "Sk0QCMAAZQAmUgfHBgI/6q4f8JENJOahJSAgG6Ek4eFy+BN4Cj/qPw==" },
  { key: "./Uniques/Armors/Skullder's Ire.d2i", value: "Sk0QCIAAZQAAigfHBgI/6q4f8JEN/OHhISAgG6Ek4fkTeAo/6j8=" },
  { key: "./Uniques/Armors/Sparking Mail.d2i", value: "Sk0QCIAAZQAIMobmBoJd+frG8VEFrNDSIiBUSQElI6AA0PoP" },
  { key: "./Uniques/Armors/Spiritforge.d2i", value: "Sk0QCIAAZQAIiud2BgISopE38VENbqGhYQC8QAB14gYGRZAsiE35Dw==" },
  { key: "./Uniques/Armors/Steel Carapice.d2i", value: "Sk0QCIAAZQAAUlfHBgLztmX58cEVcGRkJCBw2/AgwlnhNgaVzGACwa/4Dw==" },
  { key: "./Uniques/Armors/Templar's Might.d2i", value: "Sk0QCIAAZQACWhcmB4Lz5XUN8OEWxsRzIgC8DHgtkILADQTLMSheGQD6Dw==" },
  { key: "./Uniques/Armors/The Centurion.d2i", value: "Sk0QCIAAZQAIisYWBoLf+76k8REFRMDBIQ68SPCy4GWCDB9QIEJQMmpq/Qc=" },
  { key: "./Uniques/Armors/The Gladiator's Bane (Eth).d2i", value: "Sk0QCMAAZQBgWkdXB4JUGuSS8aEPugUCIiAg+8ADEdQIKsmZE8oYmRujTP8D" },
  { key: "./Uniques/Armors/The Gladiator's Bane.d2i", value: "Sk0QCIAAZQAGWkdXBwLS8X3o8aEP2AMCIiAg+8ADEdQIKsmZE8oYmRujTP8D" },
  { key: "./Uniques/Armors/The Spirit Shroud.d2i", value: "Sk0QCIAAZQBkileXBgK8SKS58BENAEFBISBYGrEoQf8k0/8=" },
  { key: "./Uniques/Armors/Toothrow.d2i", value: "Sk0QCIAAZQBoisdGBoI1XKpx8LENGgIDIwCoQOD2wQgngpI8OEEdQv0H" },
  { key: "./Uniques/Armors/Twitchthroe.d2i", value: "Sk0QCIAAZQAIOkdXB4J7SXqw8SEFWgACIgCoCFBRyD6MoAtqDOo/" },
  { key: "./Uniques/Armors/Tyrael's Might.d2i", value: "Sk0QCIAAZABkWhcmB4LoISk17XETxgQQAHwgWDoBlQJqBVQLqC3IYFBs5sGDaab/AQ==" },
  { key: "./Uniques/Armors/Venom Ward.d2i", value: "Sk0QCIAAZQBgKiY3BwKZhTjO72EFniAjIyCQacHo4mUxN0b/AQ==" },
  { key: "./Uniques/Armors/Victors Silk.d2i", value: "Sk0QCIAAZQAKEhYmBwI2VluP8cEF6MHDIyDg8VHIYn/yHw==" },
  { key: "./Uniques/Belts/Arachnid Mesh.d2i", value: "Sk0QAIAAZQQRUMc2BgIVenvY8FEXksCwAAKeJk8a1J9YUjAbLFpY+A8=" },
  { key: "./Uniques/Belts/Bladebuckle.d2i", value: "Sk0QAIAAZQBGgibGBoLedh+V70EHLIAxAUCJABUEMh9QIGJwghgj+w8=" },
  { key: "./Uniques/Belts/Gloomstrap.d2i", value: "Sk0QAIAAZQBwotcmBgKDNkVp8EEPZgDxYMALgqUNDz4KTbIs8R8=" },
  { key: "./Uniques/Belts/Goldwrap.d2i", value: "Sk0QAIAAZQAmQifGBoJmZhbS8DEHIiDRAAKPDyN4QguKYBbr4vkP" },
  { key: "./Uniques/Belts/Lenyms.d2i", value: "Sk0QAIAAZQBgwibGBoLAePyk8QEHGMCQIMHLBo8TNyluVty0uMlS/wE=" },
  { key: "./Uniques/Belts/Nightsmoke.d2i", value: "Sk0QAIAAZQAG0ibGBgKLL9PZ8SEHIACBIAENBBkfMiBCOMGTgmcFTwseOfJ/" },
  { key: "./Uniques/Belts/Nosferatu's Coil.d2i", value: "Sk0QAIAAZQCgWmc3BoLv3e6C72EXiuBwAMALj0OW6OJRJLCk+A8=" },
  { key: "./Uniques/Belts/Razortail.d2i", value: "Sk0QAIAAZQBsomcnBgL+yP+D8TEPXuDgQMALgiULCgyKDxngFAKlcIf+Aw==" },
  { key: "./Uniques/Belts/Snakecord.d2i", value: "Sk0QAIAAZQBkYifGBgINJ/4Q8BEHHOBwAIKHDxRosZQDBRSWKBndGP0H" },
  { key: "./Uniques/Belts/Snowclash.d2i", value: "Sk0QAIAAZQBookcnBoJdfg6b8VEPaiAhAYIqFs9GQ4WlNTe2ZofW8FClRzJqh8J/" },
  { key: "./Uniques/Belts/String of Ears.d2i", value: "Sk0QAIAAZQBgoscmBgIBYu/S8SEPWsDAAAKtDxkY8ZB44IFIovAf" },
  { key: "./Uniques/Belts/Thundergod's Vigor (Up).d2i", value: "Sk0QAIAAZQBMUoc2BoLyWRhh8GEPooCBAQDNABoEZCqUjEAGLoc1IrZmxCJRkh15FP4D" },
  { key: "./Uniques/Belts/Thundergod's Vigor.d2i", value: "Sk0QAIAAZQAEoocmBoLyWRhh8GEPfoCBAQDNABoEZCqUjECGNSK2ZsQiUZIdeRT+Aw==" },
  { key: "./Uniques/Belts/Verdugo's Hearty Cord.d2i", value: "Sk0QAIAAZQDAWtc2BgLwGe6N8YEXmAChYAByASYERiQelKxjPP8B" },
  { key: "./Uniques/Boots/Goblin Toe.d2i", value: "Sk0QAIAAZQBgSidGB4K4odr58eEGLCDBAAKPDxkQEYwIsgyizH8=" },
  { key: "./Uniques/Boots/Gorefoot.d2i", value: "Sk0QAIAAZQBkaidGBwJwg3Wo8MEGIuCAAIKHDxbwIXByAINaQ0iMCP8B" },
  { key: "./Uniques/Boots/Gorerider (Up).d2i", value: "Sk0QAIAAZQAQUocmBgIQ9Aut8REPooCBYQENBGRJFLYscTmAkR1SIHo0evwH" },
  { key: "./Uniques/Boots/Gorerider.d2i", value: "Sk0QAIAAZQAAgocmBgIQ9Aut8REPgICBYQENBGRJFLYsgZEdUiB6NHr8Bw==" },
  { key: "./Uniques/Boots/Hotspur.d2i", value: "Sk0QAIAAZQBoyiZGBwIgmimB77EGHMBg4MALCBQ+QODEF4oHY8DAfw==" },
  { key: "./Uniques/Boots/Infernostride.d2i", value: "Sk0QAIAAZQBAgscmBoLOWWD58dEOXMDAAIKlDxk4AYVCwWAI8URVFgODSoa4UPgP" },
  { key: "./Uniques/Boots/Marrowwalk.d2i", value: "Sk0QAIAAZQCoWtcmBoImyzDt8SEXnAABAQCNgBgEZBsUOCiAQa0pIjuZMVIoKDALsWho+A8=" },
  { key: "./Uniques/Boots/Sandstorm Trek (Eth).d2i", value: "Sk0QAMAAZSQTUGcnBgLLtFRd8REX2uDgAMDLgBcEVS3wwKDGoDQZ5SH8iv8=" },
  { key: "./Uniques/Boots/Shadowdancer.d2i", value: "Sk0QAIAAZSQTUIcmBoKfezvJ8VETpICBQUAOApktUGBkY2S8YgD0Hw==" },
  { key: "./Uniques/Boots/Silkweave (Up).d2i", value: "Sk0QAIAAZQAMUtcmBoKsLvmC7/EOmgABAYIvEMiaUFwOYGSKCv8B" },
  { key: "./Uniques/Boots/Silkweave.d2i", value: "Sk0QAIAAZQAEgtcmBoKsLvmC7/EObgABAYIvEMiaUGBkigr/AQ==" },
  { key: "./Uniques/Boots/Tearhaunch.d2i", value: "Sk0QAIAAZQCgiiZGBwJK3hTr7/EGNIDhAECJgBIEKB9acIInBc8KnhY8YFBr5ug/" },
  { key: "./Uniques/Boots/Treads of Cthon.d2i", value: "Sk0QAIAAZQCk2iZGB4L+872d79EGKACx4IAKCCg+WACEDDAyTcb/" },
  { key: "./Uniques/Boots/Wartraveler (Up).d2i", value: "Sk0QAIAAZQAQUkcnBgLzck8u8QEPnCDRAIDKABUEXxUeC5kLD4ZMEg8nCiiWYFqaeJ8eUJn/" },
  { key: "./Uniques/Boots/Wartraveler.d2i", value: "Sk0QAIAAZQBEgkcnBgJTFuM38QEPdCAhAYDKABUEXxUeC5kLD4ZMEg8nCiiWYFqaeJ8eUJn/" },
  { key: "./Uniques/Boots/Waterwalk (Up).d2i", value: "Sk0QAIAAZQBQUmcnBgLrG8Ms8eEOjuDgQMDrQJgFSBCkcZABQQZFAYP6Dw==" },
  { key: "./Uniques/Boots/Waterwalk.d2i", value: "Sk0QAIAAZQAIgmcnBgK/06Bi8eEOZOCwQMDrQJgFSBCkcZABQQZFAYP6Dw==" },
  { key: "./Uniques/Charms/Annihilus.d2i", value: "Sk0QAIAAZQAgMtYWA4IjJRnOwI2+AIAmAE0AbQDthFEKoxVGLYyq8PiT/w==" },
  { key: "./Uniques/Charms/Gheed's Fortune.d2i", value: "Sk0QAIAAZQAAOtY2AwJ7P+9BwY2z8IQgFMYrj/8=" },
  { key: "./Uniques/Class-Items/Ama/Amazon Torch.d2i", value: "Sk0QAIAAZAAAMtYmA4KAwYck7gXIAIAmAE0AbQDthFEKoxVGLYymYFnYmFJMhpnng4LCfw==" },
  { key: "./Uniques/Class-Items/Ama/Bloodraven's Charge.d2i", value: "Sk0QCIAAZQAIEtYmBgIFjQfs8MEUYGBEBHPm7gD11OAFAEBmxRceHv8B" },
  { key: "./Uniques/Class-Items/Ama/Lycander's Aim (Up).d2i", value: "Sk0QCIAAZQAGEtY2BgJDENBj76ERbk5EAJoAGgQKEZAhu5BhkPlATIG6oHgBAOg/" },
  { key: "./Uniques/Class-Items/Ama/Lycander's Flank.d2i", value: "Sk0QKIAAZQAAEtaWA4LTByN72bERMhoEAJoBNAgUIiBDdiHDIOORmAJ1kfESANB/" },
  { key: "./Uniques/Class-Items/Ama/Lycander's Flank (Eth).d2i", value: "Sk0QKMAAZQACEtaWA4LTByN72bERGhoEAJoBNAgUIiBDdiHDIOORmAJ1kfESANB/" },
  { key: "./Uniques/Class-Items/Ama/Thunderstroke.d2i", value: "Sk0QAIAAZQACEtZmBgKbS63B8CEVDAxAiYAMmYzgvy6jNRTGSwCAxpwYKE4f/gM=" },
  {
    key: "./Uniques/Class-Items/Ama/Titan's Revenge (Eth).d2i",
    value: "Sk0QAMAAZQAAEtYWBgJbsSw/75ERDAwwAkAjgBYBGbIKmQUZj8QUCIzsUwZKxksAQP08fzz/AQ==",
  },
  {
    key: "./Uniques/Class-Items/Ama/Titan's Revenge (Eth, Up).d2i",
    value: "Sk0QAMAAZQCKGtZmBgJbsSw/75ERDAg0AEAjgBYBGbIKmQUZj8QUiMsBjOxTBkrGSwBA/Tx/PP8B",
  },
  {
    key: "./Uniques/Class-Items/Assa/Assassin Torch.d2i",
    value: "Sk0QAIAAZABEMtYmAwKunrcw7gXIAIAmAE0AbQDthFEKoxVGLYymeFnYmFJMhpnng4LCfw==",
  },
  {
    key: "./Uniques/Class-Items/Assa/Bartuc's Cutthroat (Up).d2i",
    value: "Sk0QCIAAZAAAekN3BwLMbWQx7eERiooEABoBtAjIkFXILMh4JKZYXA5jZHdQ8JIByH8=",
  },
  {
    key: "./Uniques/Class-Items/Assa/Bartuc's Cutthroat (Up, Eth).d2i",
    value: "Sk0QCMAAZAAAekN3BwLMbWQx7eERiooEABoBtAjIkFXILMh4JKZYXA5jZHdQ8JIByH8=",
  },
  { key: "./Uniques/Class-Items/Assa/Jadetalon.d2i", value: "Sk0QAIAAZQAKcnMnBoK7GPTM8UETcFJEgAfvBFkKshVkLch8PMbIeMUAiJcMgP4D" },
  {
    key: "./Uniques/Class-Items/Barb/Arreat's Face (Up).d2i",
    value: "Sk0QCIAAZQBOIhZmBoJDQk128HERZHFzIwDQCKBBQHYCKgXUCqgWUDwMUyguhzGyOyh4gQDoPw==",
  },
  {
    key: "./Uniques/Class-Items/Barb/Arreat's Face.d2i",
    value: "Sk0QCIAAZQAAIhYWBoJDQk128HERBnFzIwDQCKBBQHYCKgXUCqgWUDwMU6gxsjsoeIEA6D8=",
  },
  {
    key: "./Uniques/Class-Items/Barb/Barbarian Torch.d2i",
    value: "Sk0QAIAAZAAEOtYmA4KVvQEX7gXIAIAmAE0AbQDthFEKoxVGLYymcFnYmFJMhpnng4LCfw==",
  },
  { key: "./Uniques/Class-Items/Barb/Demonhorn's Edge.d2i", value: "Sk0QCIAAZQBKIhZGBoIg7s+W8VEUTtHyISCA4mFw0uzi4QUCMF4hAOMlArD/" },
  { key: "./Uniques/Class-Items/Barb/Halaberd's Reign.d2i", value: "Sk0QCIAAZQAEIhZWBgIiUu9P8JEWVCEjIyCoUlJPocag1lTSmk3iFQKQ/w==" },
  {
    key: "./Uniques/Class-Items/Barb/Wolfhowl Fury.d2i",
    value: "Sk0QCIAAZQAIIhY2BgKybzoJwTEWQjEyIgC8CHgNeEGwFOabEQacEQadwUsEYMyediQk/gM=",
  },
  { key: "./Uniques/Class-Items/Dru/Cerebus' Bite.d2i", value: "Sk0QCIAAZQBKQiYnBgKDXWsp72ETOEEBISAw4qFYg053GB0K8UoB4H8=" },
  { key: "./Uniques/Class-Items/Dru/Druid Torch.d2i", value: "Sk0QAIAAZAAyMtYmA4KVvQEX7gXIAIAmAE0AbQDthFEKoxVGLYymdFnYmFJMhpnng4LCfw==" },
  {
    key: "./Uniques/Class-Items/Dru/Jalal's Mane (Up).d2i",
    value: "Sk0QCIAAZQAISiZnBoKvlVhm7/ERUkFBIQDQBKBBQHYCKgXUCqgWUFMqLocxsjsoFBV4pQDoPw==",
  },
  { key: "./Uniques/Class-Items/Dru/Ravenlore.d2i", value: "Sk0QCIAAZQBKQiZXBoLjnUJa8OEVTEHRIAL4IFg6sZRiacVSi6U13c5LBWBNKf4D" },
  { key: "./Uniques/Class-Items/Dru/Spiritkeeper.d2i", value: "Sk0QCIAAZQBOQiZHBgKnp1X/8XEURkEBISD4OqHlQk2pxqAiOShl/gM=" },
  {
    key: "./Uniques/Class-Items/Necro/Arm of King Leoric.d2i",
    value: "Sk0QCIAAZQBCkiN2B4Lj3D9k8NEIHh5EGs+aIltjZGuaaA0U8YoAEC8JACUTsFAkU7ooZFP+Aw==",
  },
  { key: "./Uniques/Class-Items/Necro/Boneflame.d2i", value: "Sk0QCIAAZQBK4lZWBoKLVr1bwVEVOkHRICBYOgGVAmoFVAuoKRoYVLKhicd/" },
  { key: "./Uniques/Class-Items/Necro/Boneshade.d2i", value: "Sk0QCIAAZQBQciN2B4I+sr5H8PEVIhbEFClNa82QriHSNU62hsrWdNF/" },
  { key: "./Uniques/Class-Items/Necro/Darkforge Spawn.d2i", value: "Sk0QCIAAZQBK4lZmBgIaOa7q8aEUPkHhICDQakKlkfGCABivCIDxkgDYfw==" },
  { key: "./Uniques/Class-Items/Necro/Deaths's Web.d2i", value: "Sk0QCIAAZQAycnN2BwKGoiOj8bESJCCEFcYfKWLwigAQVJn/" },
  {
    key: "./Uniques/Class-Items/Necro/Homunculus (Up).d2i",
    value: "Sk0QCIAAZQBE6lZmBoIvAQNzwYERPEFBIQLQICCjgG4IOaGVQmuFVgutKRKXgxmZogIvCAD9Bw==",
  },
  {
    key: "./Uniques/Class-Items/Necro/Necromancer Torch.d2i",
    value: "Sk0QAIAAZAAIOtYmA4KVvQEX7gXIAIAmAE0AbQDthFEKoxVGLYymaFnYmFJMhpnng4LCfw==",
  },
  { key: "./Uniques/Class-Items/Pala/Alma Negra.d2i", value: "Sk0QCIAAZQAIChc2BgLzj4eF75EUXkEkJCBIi7BkCQVqRDJlMiO78+U/" },
  { key: "./Uniques/Class-Items/Pala/Astreon's Ironward.d2i", value: "Sk0QCIAAZQAQcnM3BwI8hz3P8cEXjFhEBJEiRRw0oOB18bxJc4cbopClDC8MAP4H" },
  { key: "./Uniques/Class-Items/Pala/Dragonscale.d2i", value: "Sk0QCIAAZQAEChdWBoJMjhb68bEVmBEUJADkQECGosCYnhvGh+KIkjTIfw==" },
  {
    key: "./Uniques/Class-Items/Pala/Herald of Zakarum (Up).d2i",
    value: "Sk0QCIAAZABgChdWBoKbOMhG7dERmBEUJADQDKBBQEbBO0GWgmwFWQuyKROXgxnZHRS8MAD0Hw==",
  },
  {
    key: "./Uniques/Class-Items/Pala/Herald of Zakarum (Up, Eth).d2i",
    value: "Sk0QCMAAZABkChdWBoIme3Fu7dERWBIUJADQDKBBQEbBO0GWgmwFWQuyKROXgxnZHRS8MAD0Hw==",
  },
  {
    key: "./Uniques/Class-Items/Pala/Herald of Zakarum.d2i",
    value: "Sk0QCIAAZAAIAheWA4LJtzIw7dERZiEjIwDQDKBBQEbBO0GWgmwFWQuyKZMZ2R0UvDAA9B8=",
  },
  {
    key: "./Uniques/Class-Items/Pala/Paladin Torch.d2i",
    value: "Sk0QAIAAZABgOtYmA4KVvQEX7gXIAIAmAE0AbQDthFEKoxVGLYymbFnYmFJMhpnng4LCfw==",
  },
  { key: "./Uniques/Class-Items/Sorc/Death's Fathom.d2i", value: "Sk0QCIAAZQAA8iZmBgId/9CF8SEWZGTECa0UWlOyNKilUP4D" },
  { key: "./Uniques/Class-Items/Sorc/Eschutas Temper.d2i", value: "Sk0QCIAAZQAA8iY2BoI7S1SE8fEWPDhEAN+ULA0vqRGlRv4D" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (Blizzard).d2i", value: "Sk0QCIAAZQBgWleXBoI9vhPS8GEWsENBITY8fPBAGtSaHUsaRGmQpUH+Aw==" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (CL).d2i", value: "Sk0QCIAAZQAAWleXBoI9vhPS8GEWsENBITY8fPBAGtSaGksaRGmQpUH+Aw==" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (FB).d2i", value: "Sk0QCIAAZQAEWleXBoI9vhPS8GEWsENBITY8fPBAGtSaF0saRGmQpUH+Aw==" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (Fire Mast).d2i", value: "Sk0QCIAAZQAIWleXBoI9vhPS8GEWsENBITY8fPBAGtSaHksaRGmQpUH+Aw==" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (Lightning).d2i", value: "Sk0QCIAAZQAAWleXBoI9vhPS8GEWsENBITY8fPBAGtSaGEsaRGmQpUH+Aw==" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (Meteor).d2i", value: "Sk0QCIAAZQBkWleXBoI9vhPS8GEWsENBITY8fPBAGtQaHEsaRGmQpUH+Aw==" },
  { key: "./Uniques/Class-Items/Sorc/Ormus' Robes (Orb).d2i", value: "Sk0QCIAAZQBoWleXBoI9vhPS8GEWsENBITY8fPBAGtQaIEsaRGmQpUH+Aw==" },
  {
    key: "./Uniques/Class-Items/Sorc/Sorceress Torch.d2i",
    value: "Sk0QAIAAZABiOtYmA4KVvQEX7gXIAIAmAE0AbQDthFEKoxVGLYymZFnYmFJMhpnng4LCfw==",
  },
  { key: "./Uniques/Class-Items/Sorc/The Oculus.d2i", value: "Sk0QCIAAZQAy8iYWBoLKv83T8cERZFREANoAGgQKJ4xSGK0wamEExXJKlkamqJAssCHzHw==" },
  { key: "./Uniques/Gloves/Bloodfist.d2i", value: "Sk0QAIAAZQAAYnfGBgJA77z+8XEGIuDg4AASCBQqFBeKDxTo4hkj+1T8Bw==" },
  { key: "./Uniques/Gloves/Chance Guards.d2i", value: "Sk0QAIAAZQBA0nbGBoLEgWEJ74EGKAABAYKHCRl8yMATllAYs9h/" },
  { key: "./Uniques/Gloves/Dracul's Grasp.d2i", value: "Sk0QAIAAZQCkWmd3BgI3hrDA8cEWmODgAMALBDw8FFYUhzLGFCkK/wE=" },
  { key: "./Uniques/Gloves/Frostburn.d2i", value: "Sk0QAIAAZQAEgnbGBgJOJw0w76EGNICBAQKFCAUKfECBjQADMk3k/w==" },
  { key: "./Uniques/Gloves/Ghoulhide.d2i", value: "Sk0QAIAAZQAAgtd2BgLR4vrh8aEObgAB4QANCL58FOhB9qD/" },
  { key: "./Uniques/Gloves/Gravepalm.d2i", value: "Sk0QAIAAZQAAgmd3BoJhn3418ZEOZODgAIBKABUEWnq48UHqPw==" },
  { key: "./Uniques/Gloves/Hellmouth.d2i", value: "Sk0QAIAAZQAEgod2BgIeOivb8cEOgICBAQIyGA9Ikjw8ehgjcBAYY8Ih/Ac=" },
  { key: "./Uniques/Gloves/Lavagout (Up).d2i", value: "Sk0QAIAAZQDIWkd3BoL71en38bEOnCAhAQKyE0owGlwkoeBy6IKy05hCg+A/" },
  { key: "./Uniques/Gloves/Lavagout.d2i", value: "Sk0QAIAAZQBEgkd3BoL71en38bEOdCAhAQKyE0owGlwkoeiCstOYQoPgPw==" },
  { key: "./Uniques/Gloves/Magefist.d2i", value: "Sk0QAIAAZQDISnfGBoIpFpYL8JEGLCDxAIKHDRkfKAAjwEAalJ/kPw==" },
  { key: "./Uniques/Gloves/Souldrain.d2i", value: "Sk0QAIAAZQAEUtd2BoKf6keE74ETnAABAQIeHgcfBzxOYwMSiP8=" },
  { key: "./Uniques/Gloves/Steelrend.d2i", value: "Sk0QAIAAZQBoWod2BgLpTuKe8XEYkoBBAQBNBB48PnADkeI/" },
  { key: "./Uniques/Gloves/The Hand of Broc.d2i", value: "Sk0QAIAAZQBEwnbGBoKyNk7t72EGHMDAIAENBAofKNCCh8fAx+A/" },
  { key: "./Uniques/Gloves/Venom Grip.d2i", value: "Sk0QAIAAZQAIgsd2BgK49yS58YEOXMDAAAKoDyNoAeWi5MgkEzI8CogK/wE=" },
  { key: "./Uniques/Helmets/Andariel's Visage.d2i", value: "Sk0QCIAAZQAEUje3BoIQUQT68ZEVSkFBIQD4QLB0gqIFngvFQ9EF9UfJHi4ezAaLKCj+Aw==" },
  { key: "./Uniques/Helmets/Biggin's Bonnet.d2i", value: "Sk0QCIAAZQAIMhYGB4KB5i5u73EEHsDAIA68SPASwYOHCR58wMB/" },
  { key: "./Uniques/Helmets/Blackhorn's Face.d2i", value: "Sk0QCIAAZQAAgje3BgJVcy0h8fEMwkBBISBwSxFUJwAoR6JYovwH" },
  { key: "./Uniques/Helmets/Coif of Glory.d2i", value: "Sk0QCIAAZQBIgsbWBoJJ+dDw8ZEEMoCBIT5QAASZFEFxAoDOfw==" },
  { key: "./Uniques/Helmets/Crown of Ages.d2i", value: "Sk0QCIAAZQAsUifnBgJeNOmT8YEVYCEDQyDI+AAKEg8noFJArYBqATVG9ieY/gc=" },
  { key: "./Uniques/Helmets/Crown of Thieves (Up, Eth).d2i", value: "Sk0QCMAAZQBEUifnBgIxUcb76+EMAiIjIwTkDkhJMAQB2YkpHownyLgc/gM=" },
  { key: "./Uniques/Helmets/Crown of Thieves.d2i", value: "Sk0QCIAAZQBAgifnBgIiOedZ8eEM+CAjIwTkDkhJMAQB2YkpHownyP4D" },
  { key: "./Uniques/Helmets/Darksight Helm.d2i", value: "Sk0QCIAAZQAEgofGBoLpt0ei8cEMruDhIU5o+ShkgUyTDUcYmBUIeXhYg/4D" },
  { key: "./Uniques/Helmets/Duskdeep.d2i", value: "Sk0QCIAAZQAMYobGBoL78XTA8aEESuDhISDIsIDAgPjgARHHiaAUQSuCWgRlEVCI/w==" },
  { key: "./Uniques/Helmets/Giantskull.d2i", value: "Sk0QCIAAZQAEUoeWA4K4xLzz77EXDIGCQgAMfVBKlAAixX8=" },
  { key: "./Uniques/Helmets/Griffon's Eye.d2i", value: "Sk0QCIAAZQBIMpY2AwLhwoEy8QEVeEAhIT5II03rT5QacUrxHw==" },
  { key: "./Uniques/Helmets/Harlequin Crest.d2i", value: "Sk0QCIAAZQACUhcGBwLhaR6G8YEPLsHAIACIBBAJEA0QkVCAYvlH2JhszH8=" },
  { key: "./Uniques/Helmets/Howltusk.d2i", value: "Sk0QCIAAZQBMcobWBoJx/AqG8MEEXICCIiBAGSE4GUQJwAHJGf8D" },
  { key: "./Uniques/Helmets/Kira's Guardian.d2i", value: "Sk0QKIAAZAAGMpYmA4LteFIh7VEWeJCRIT4I4gReCrwVeC3wMh2D+g8=" },
  { key: "./Uniques/Helmets/Nightwing's Veil.d2i", value: "Sk0QCIAAZQACUofWBgJrumaj73EVVIEyIgTQIODZImPnH1VKLA3yHw==" },
  { key: "./Uniques/Helmets/Peasent Crown.d2i", value: "Sk0QCIAAZQBEghcGB4LLjPv/8ZEMgMDAIALQBtAgkFGighn9yX8=" },
  { key: "./Uniques/Helmets/Rockstopper.d2i", value: "Sk0QCIAAZQAIgrcGBwJA9eqX8aEMkiAhIQa8IHAjoXCCLIXWCq0xsv8=" },
  { key: "./Uniques/Helmets/Stealskull.d2i", value: "Sk0QCIAAZQBIgsfWBgILX0VN77EMpoCBISDA41HwUYBi2cUzxvMf" },
  { key: "./Uniques/Helmets/Steelshade.d2i", value: "Sk0QCIAAZQAIUsfWBoJ0erOq8JESQIGBISAI8oFQAj9a/Ac=" },
  { key: "./Uniques/Helmets/Tarnhelm.d2i", value: "Sk0QCIAAZQAQMrcGB4K5mmvd8YEEKiAhIZ68gmL5J/8B" },
  { key: "./Uniques/Helmets/The Face of Horror.d2i", value: "Sk0QCIAAZQBQ0ja3BoLgarbo7+EEOEBBIQDQfBjBCZ4UPCt4WvDA+ekx8h8=" },
  { key: "./Uniques/Helmets/Undead Crown.d2i", value: "Sk0QCIAAZQAAOibnBgIJTcbt8dEEcCAjIyDw+CCDFmQ8CmuKzE49RviQ8x8=" },
  { key: "./Uniques/Helmets/Valkiry Wing (Up).d2i", value: "Sk0QCIAAZQDAWofWBoJY9mc+79EMUoGCIiAgmwJxOYBBjUEpIvwH" },
  { key: "./Uniques/Helmets/Valkiry Wing.d2i", value: "Sk0QCIAAZQAMgofWBoJY9mc+79EM2oCCIiAgmwKBQY1BKSL8Bw==" },
  { key: "./Uniques/Helmets/Vampiregaze (Up).d2i", value: "Sk0QCIAAZQDEWoeWA4JuePnh8QENToGCIiCQGfGQoLBhYIGMB8IHgstB0+g/" },
  { key: "./Uniques/Helmets/Vampiregaze.d2i", value: "Sk0QCIAAZQBMgoeWA4JuePnh8QENEIGCIiCQGUGReLBhYIGMB8IHQtPoPw==" },
  { key: "./Uniques/Helmets/Veil of Steel.d2i", value: "Sk0QKIAAZAAMUofWBoKLKj9M7ZEPVIHCI06QpSBbQdaCDAIPAC8DXlkgCcUHS/wH" },
  { key: "./Uniques/Helmets/Wormskull.d2i", value: "Sk0QCIAAZQAEKobWBgLn5eP98bEEWICCIhKotFjKYYYZyHgUpij/AQ==" },
  { key: "./Uniques/Jewels/Fire Facet (Die).d2i", value: "Sk0QAIAAZQCkqlZ2BwIjIqXj8SXFACOiRbEPB3LSG00L/gM=" },
  { key: "./Uniques/Jewels/Fire Facet (Lvl).d2i", value: "Sk0QAIAAZQAIolZ2BwJSIy+9wgXHACOixbHOBXLSG00L/gM=" },
  { key: "./Uniques/Jewels/Ice Facet (Die).d2i", value: "Sk0QAIAAZQAIqlZ2BwKQjBIhwa3EYAPDxECxcgfy0htPC/4D" },
  { key: "./Uniques/Jewels/Ice Facet (Lvl).d2i", value: "Sk0QAIAAZQAoolZ2BwL+wTsvwYXGYAPDxMCxlQXy0htPC/4D" },
  { key: "./Uniques/Jewels/Lightning Facet (Die).d2i", value: "Sk0QAIAAZQAqqlZ2BwJMqEk+wS3EICNQothbA1npDacF/wE=" },
  { key: "./Uniques/Jewels/Lightning Facet (Lvl).d2i", value: "Sk0QAIAAZQAKolZ2BwKZAcaxwAXGICNQ4lgKA1npDacF/wE=" },
  { key: "./Uniques/Jewels/Poison Facet (Die).d2i", value: "Sk0QAIAAZQAOolZ2BwJi8NtZwaXFkGOXXWQUm7kgM70BteA/" },
  { key: "./Uniques/Jewels/Poison Facet (Lvl).d2i", value: "Sk0QAIAAZQAqolZ2BwJo0QrA8YXHkGOXXWQcuywiM70BteA/" },
  { key: "./Uniques/Rings/Bul Katho's Wedding Band.d2i", value: "Sk0QAIAAZQCEKpfmBoLzviD98CWGsECKR+FPsBH/AQ==" },
  { key: "./Uniques/Rings/Carrion Wind.d2i", value: "Sk0QAIAAZQBkKpfmBgKM8I+g7wW9AAJUizQeCTmKsQYeRDKFCwWzypuHh/8=" },
  { key: "./Uniques/Rings/Dwarf Star.d2i", value: "Sk0QAIAAZQAAIpfmBgLdQ3Kx8SWJcADJAiQODyOeJ8gcPf4D" },
  { key: "./Uniques/Rings/Manald Heal.d2i", value: "Sk0QAIAAZQBAIpfmBgIabioZ8ZU8cIDGBgofByXmfw==" },
  { key: "./Uniques/Rings/Nagelring.d2i", value: "Sk0QAIAAZQAgIpfmBgKQYC/j8QU8MGGJEYOTARTB/w==" },
  { key: "./Uniques/Rings/Nature's Peace.d2i", value: "Sk0QAIAAZQBEKpfmBgK1D7iX7yWWIGJpAcVmnQCzQpyNjf8=" },
  { key: "./Uniques/Rings/Raven Frost.d2i", value: "Sk0QAIAAZQAkKpfmBoLHH/Yo8JWJIICWAGmCPjYeWpBRomT6Hw==" },
  { key: "./Uniques/Rings/Stone of Jordan.d2i", value: "Sk0QAIAAZeQOIJfmBgKpNuOp8RU9kIBGRsBAk/FP/gM=" },
  { key: "./Uniques/Rings/Wisp Projector.d2i", value: "Sk0QAIAAZQAEKpfmBgKWYPSq742fAAUPEsUYFIOCmSDOwwOzgp2GBmaHPQsL/wE=" },
  { key: "./Uniques/Shields/Blackoak Shield.d2i", value: "Sk0QCIAAZQBAUtfGBgL/pBP078EPDEHlIiAgS9JixmhnsgIJAjalG6Gu+A8=" },
  { key: "./Uniques/Shields/Bverrit Keep.d2i", value: "Sk0QCIAAZQAAQvd2BwJzsYH78EEGSMDDIwCUQMBDQfmAghHFib4kZP8B" },
  { key: "./Uniques/Shields/Headhunter's Glory.d2i", value: "Sk0QCIAAZQAIUjeHBgLz2EB58WEYWKFUYj64BoTXE1AttKwc/gM=" },
  { key: "./Uniques/Shields/Kerke's Sanctuary.d2i", value: "Sk0QCIAAZQAAgvd2BwIJuQbO8UEOsoCEJCDAo+CJgEZIJ6BSQK2AagGVhExJ+x8=" },
  { key: "./Uniques/Shields/Lance Guard.d2i", value: "Sk0QCIAAZQAEgge3BoKUDMTj8XEOsnBzIw5IgYDHyWuMTM7TiPIf" },
  { key: "./Uniques/Shields/Lidless Wall (Up).d2i", value: "Sk0QCIAAZQAIUjeHBoJx+qbK8GEObqGkJAKoIAhqQmUpLoc0qD9RVPgP" },
  { key: "./Uniques/Shields/Lidless Wall.d2i", value: "Sk0QCIAAZQCgijeHBoJx+qbK8GEOQmEUJAKoIAhqQmWpNKg/UVT4Dw==" },
  { key: "./Uniques/Shields/Medusa's Gaze.d2i", value: "Sk0QCIAAZQAMUvd2B4IAsxUF79EVWMFVIyDQWiHII2GJUoyFgZzs2ELxHw==" },
  { key: "./Uniques/Shields/Mosers Blessed Circle (Up).d2i", value: "Sk0QCIAAZQAOUtfGBgJYoIL88BEOCkFFRSBwo5CdWEqxtGKpxRKXgxnZfw==" },
  { key: "./Uniques/Shields/Mosers Blessed Circle.d2i", value: "Sk0QCIAAZQAMgtfGBgJYoIL88BEOhAAERCBwo5CdWEqxtGKpxZIZ2X8=" },
  { key: "./Uniques/Shields/Pelta Lunata.d2i", value: "Sk0QCIAAZQAEIlY3BgLztKd38OEFIsDAIACIBFANUEFAQYH6gIIkDGZ4/wE=" },
  { key: "./Uniques/Shields/Radimant's Sphere.d2i", value: "Sk0QCIAAZQAQgkc3BwI1kh2G8FEO0ABFJiAgo0C16MvBDDNkklCYQSUruCgwM6ZAQfkP" },
  { key: "./Uniques/Shields/Spike Thorn.d2i", value: "Sk0QCIAAZQAMUge3BoKTrk7I8bEWXDE1JSBYIkGRRH+MzN36Dw==" },
  { key: "./Uniques/Shields/Spirit Ward.d2i", value: "Sk0QCIAAZQAQUkc3BwK5fGmY8UEWakFGJiDQouCd0EqhtUKrhZaZVqVFMmShwn8=" },
  { key: "./Uniques/Shields/Steelclash.d2i", value: "Sk0QCIAAZQAGspZGBwK950E47zEGOuDhISCQoZB98ICI4URQiqAVQS2CklBMWbKcGdR/" },
  { key: "./Uniques/Shields/Stormchaser.d2i", value: "Sk0QCIAAZQAAiid3BoKHtl3r8SEOkODjIyBwm2AJBSoFmYyABzMeO5MZOxCSFfUQ/gM=" },
  { key: "./Uniques/Shields/Stormguild.d2i", value: "Sk0QCIAAZQAIwiZ3BoIF9F6g8QEGMoCBISDwoOB9QMGIIMWSjMCAJA+Axn8=" },
  { key: "./Uniques/Shields/Stormshield (Eth).d2i", value: "Sk0QCMAAZQAAUpdGBwIRlXNf8dEPnmFlJQD4UMhIjKRYWuFm5gZIYWrN+w8=" },
  { key: "./Uniques/Shields/Stormshield.d2i", value: "Sk0QCIAAZQAQUpdGBwIRlXNf8dEPKGEVJAD4UMhIjKRYWuFm5gZIYWrN+w8=" },
  { key: "./Uniques/Shields/Swordback Hold.d2i", value: "Sk0QCIAAZQAMMge3BgKQksRP8SEGSICCIiDwoEB9oIATxSEZI8J/" },
  { key: "./Uniques/Shields/The Ward.d2i", value: "Sk0QCIAAZQAQckY3BwJdiNGN8VEGXICCIgCoQCBDQfkggxHCCbIUZCvIWpD9Bw==" },
  {
    key: "./Uniques/Shields/Tiamat's Rebuke.d2i",
    value: "Sk0QCIAAZQAEipdGB4Kx34zP7zEOnMDEJCAgOzGVYmrFVIspGCNfZAR42NioYZkEJVnCQiHZAUMhmeHD4D8=",
  },
  { key: "./Uniques/Shields/Umbral Disk.d2i", value: "Sk0QCIAAZQAAOtfGBoIZi5rk8PEFKgABIQSoDtCAIIOC9wEFSR6ySJzAfw==" },
  { key: "./Uniques/Shields/Visceratuant.d2i", value: "Sk0QCIAAZQBMglc3BoLO2SYS8AEOeEBEJCBYouBNSczIAKn/" },
  { key: "./Uniques/Shields/Wall of the Eyeless.d2i", value: "Sk0QCIAAZQAEKjaHBoJuHrzr8BEGUoCCIiCg+ECBFkY+BmlQigr/AQ==" },
  { key: "./Uniques/Weapons/Axe/Elite/Cranebeak.d2i", value: "Sk0QCIAAZQAAetMGBwKbTpNy8fEXNDREBJYsZQQxQbHswqOTYYZ08/DwHw==" },
  { key: "./Uniques/Weapons/Axe/Elite/Deathcleaver.d2i", value: "Sk0QCIAAZQAEenMXBgI21BXn8aETNDREBIwYrSS68OiEGgn/Aw==" },
  { key: "./Uniques/Weapons/Axe/Elite/Ethereal Edge.d2i", value: "Sk0QCIAAZQAIeiMWBoK9r1DK8UEURkZEBFq0JnjVpZWH2yLFIwam/wE=" },
  { key: "./Uniques/Weapons/Axe/Elite/Executioner's Justice.d2i", value: "Sk0QCIAAZQBgenOWBgI0uWcK77ETZGREBJEiu8johBBliBlXyP4D" },
  { key: "./Uniques/Weapons/Axe/Elite/Hellslayer.d2i", value: "Sk0QCIAAZQBkeiNGBwJYsx3M8OEPUFDEgRwRyJCBYalvGPWCYhvGjfhG/Ac=" },
  {
    key: "./Uniques/Weapons/Axe/Elite/Messerschmidt's Reaver.d2i",
    value: "Sk0QCIAAZQBoenMWBoJeeLaX8fEPZGQEgJcALwGvAa8IyJDBoICXJOMOnm3Ufw==",
  },
  { key: "./Uniques/Weapons/Axe/Elite/Razoredge.d2i", value: "Sk0QCIAAZQAAcoMWBoIbXUMW72ESODhEhHDhuvDohA7JGsn+Aw==" },
  { key: "./Uniques/Weapons/Axe/Elite/Runemaster.d2i", value: "Sk0QCIAAZQAIciMTBgI5N7DA8ZETMBhUBIcOWZRM/wM=" },
  {
    key: "./Uniques/Weapons/Axe/Exceptional/Boneslayer Blade.d2i",
    value: "Sk0QCIAAZQAAknMWBgJjUSXA8ZEIZGQEAJQI3Lh1Qd25kYwqQ8aMKgMZmR5lT/kP",
  },
  { key: "./Uniques/Weapons/Axe/Exceptional/Butcher's Pupil.d2i", value: "Sk0QCIAAZQAEkhOGBwIpmtFt7yEIMDBEBGTIKngWZF1khzKNRpj+Bw==" },
  { key: "./Uniques/Weapons/Axe/Exceptional/Coldkill.d2i", value: "Sk0QCIAAZQAIkoMWBoJS5AtV8BEIODhEBF++VgSxeDZQUMh0kRlTWlAkK1hQ/Ac=" },
  { key: "./Uniques/Weapons/Axe/Exceptional/Guardian Naga.d2i", value: "Sk0QCIAAZQAOknMXBoIrbN9e8FEINDREBFq0LFBaQOUACCB9Th7GEC4K/wE=" },
  { key: "./Uniques/Weapons/Axe/Exceptional/Islestrike.d2i", value: "Sk0QCIAAZQAKkiMTBgLaM8uc7zEIMDAEAJUAKgGqAaoIvnyBkDGlWpMua/AFUeY/" },
  { key: "./Uniques/Weapons/Axe/Exceptional/Pompe's Wrath.d2i", value: "Sk0QCIAAZQAAmtMGBwL4Kp5t70EINDREBFWqYIxYihKwJDOG0EP4Dw==" },
  {
    key: "./Uniques/Weapons/Axe/Exceptional/Spellsteel.d2i",
    value: "Sk0QCIAAZQAEmiMWBgLmLki68XEIRkZEAsIIpUptyBjxbEFJ42EW2EBBwWy4wsODmVIGGRkzJhwenv8=",
  },
  {
    key: "./Uniques/Weapons/Axe/Exceptional/Stormrider.d2i",
    value: "Sk0QCIAAZQAImiNGBwJJzfBE8YEIUFBEBDJkLowYljICZJLIAHrGKBMUxpQaCskKEx7/AQ==",
  },
  { key: "./Uniques/Weapons/Axe/Exceptional/The Minataur.d2i", value: "Sk0QCIAAZQBgmnOWBgKrFgSK8aEIZGQEAJoIyJBdoDB44gjsROSxJPsP" },
  { key: "./Uniques/Weapons/Axe/Exceptional/Warlord's Trust.d2i", value: "Sk0QCIAAZQBkmsMWBgKl3uyH8WEIPDxEhFevPlThBE8KnhU8LXiUyN8Iftl/" },
  { key: "./Uniques/Weapons/Axe/Normal/Axe of Fechmar.d2i", value: "Sk0QCIAAZQAAwhaGBwKMmXdy71EAPDxEBC1aVpBlMUPjPw==" },
  { key: "./Uniques/Weapons/Axe/Normal/Bladebone.d2i", value: "Sk0QCIAAZQAEIhOGB4KPygj48SEAMDBEBBkyPngABgKDLig9ePig8h8=" },
  { key: "./Uniques/Weapons/Axe/Normal/Brainhew.d2i", value: "Sk0QCIAAZQAIchaGBwLGKML18YEAZGREgpwIUKBccGA8jPDRyIL/AQ==" },
  { key: "./Uniques/Weapons/Axe/Normal/Deathspade.d2i", value: "Sk0QCIAAZQAMEoZXBgIAIUhV7xEAMBxEBCNGKiBxAndGKCL8Bw==" },
  { key: "./Uniques/Weapons/Axe/Normal/Goreshovel.d2i", value: "Sk0QCIAAZQAQIhaGB4Lh2OCr8WEARkYEgJwIMmRgSHSRHeL9Bw==" },
  { key: "./Uniques/Weapons/Axe/Normal/Humongous.d2i", value: "Sk0QCIAAZQAAepaGB4IiWF+98ZEAZGQEAJ8IePBcQDBktuAhCv0H" },
  { key: "./Uniques/Weapons/Axe/Normal/Rakescar.d2i", value: "Sk0QCIAAZQAEeheGBwJNBAzN8UEANDREBEuWJsjQgiwHIIAs6SL7Dw==" },
  { key: "./Uniques/Weapons/Axe/Normal/Skull Splitter.d2i", value: "Sk0QCIAAZQAI2gaXBoLJpFT08DEANBxEBDJkJpCxgUJGwEAcwaHHfw==" },
  { key: "./Uniques/Weapons/Axe/Normal/The Chieftan.d2i", value: "Sk0QCIAAZQBgKkaHB4JzTPgV8HEAUFBEBDJkThilMFph1MJIRoBCF5Qiw38=" },
  { key: "./Uniques/Weapons/Axe/Normal/The Gnasher.d2i", value: "Sk0QCIAAZQBkihaGB4JI+bK68QEAODgEAJQIRowckiGi/Ac=" },
  { key: "./Uniques/Weapons/Bow/Elite/Windforce.d2i", value: "Sk0QCIAAZQAEYsN2B4Jbvi7u8aEQbkgEABUBpQj69HHw8IGIEuiC0pb9Bw==" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Cliffkiller.d2i", value: "Sk0QCIAAZQAEgsOGA4LU5+Lu8REMWFjEASkRzJm7oGDwgIASJTAF+g8=" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Endlesshail.d2i", value: "Sk0QCIAAZQAMgjMmBgJgO3GK8fELSEhEAqQI3LiBkLGiysaDh6U1Gvof" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Godstrike Arch.d2i", value: "Sk0QCIAAZQAQgsN2B4LjojN98TEMbm5EBH36lKhdjHdU5eGmh5uxI4/Cfw==" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Kuko Shakaku.d2i", value: "Sk0QCIAAZQAAisMmBgJRL7CX8eELODhEBFq0YKDQWrNhnGSeDrwAAPYf" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Magewrath.d2i", value: "Sk0QCIAAZQAIijN3BwJa8/7+8SEMYEyEAFUES5Ym6HMhwyAb0fh4TEHWWFicwH8=" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Riphook.d2i", value: "Sk0QCIAAZQCEioMmBgICLgnb8dELQEBEgqEI3LjxUHSRHfJY8vwH" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Skystrike.d2i", value: "Sk0QCIAAZQCIijMnBoJehOZ/8cELKChEAFUEZMgmkCEj0GcK0kVmzMBB8B8=" },
  { key: "./Uniques/Weapons/Bow/Exceptional/Whichwild String.d2i", value: "Sk0QCIAAZQCIijOHA4LOimHB8QEMUFBIBFWqTmil0Fqh1UKrE8VYIYRAH/If" },
  { key: "./Uniques/Weapons/Bow/Normal/Blastbark.d2i", value: "Sk0QCIAAZQAAwnYnBgIUVCvv8SEEbm4EgJIIggT5GExB1kDQfw==" },
  { key: "./Uniques/Weapons/Bow/Normal/Hellclap.d2i", value: "Sk0QCIAAZQAEMncnBgJyz0977xEEYGCEAFYELVomLHFCC8aDjC4eP8l/" },
  { key: "./Uniques/Weapons/Bow/Normal/Pluckeye.d2i", value: "Sk0QCIAAZQAIMid2BwL6VFfs8bEDKCjEARURyJCZwIGPQRZTJPgP" },
  { key: "./Uniques/Weapons/Bow/Normal/Raven Claw.d2i", value: "Sk0QCIAAZQAMwiZ2BwLwn/7Z8dEDODgEgBEBowhGjNwx4mnwHw==" },
  { key: "./Uniques/Weapons/Bow/Normal/Rogue's Bow.d2i", value: "Sk0QCIAAZQAQMiZ2BwLGJqf38eEDSEhEBB48JvBwgicFzwqeFjxdjHrwNPL8Bw==" },
  { key: "./Uniques/Weapons/Bow/Normal/Stormstrike.d2i", value: "Sk0QCIAAZQAAOicmBgIl1R/P8fEDUFAEAJQIWrRM4CDFkozAA06Z/w==" },
  { key: "./Uniques/Weapons/Bow/Normal/Witherstring.d2i", value: "Sk0QCIAAZQAEiiZ2BwLrdK6T8MEDQEBEBBkyJshwIcAw6CLrNPgP" },
  { key: "./Uniques/Weapons/Bow/Normal/Wizendraw.d2i", value: "Sk0QCIAAZQAIyiYmBoLx1e9N8AEEWFhEgFcCnwhQoEwgYwVTF1SnwNOR/w==" },
  { key: "./Uniques/Weapons/Crossbow/Elite/Gutsiphon.d2i", value: "Sk0QCIAAZQAAYiOHBwJtrzXc8VESUFBEBG7ceEgOhSxlOIX+Aw==" },
  { key: "./Uniques/Weapons/Crossbow/Elite/Hellrack.d2i", value: "Sk0QCIAAZQAEYoOGBwKmv9sI74EUZGRIBHPmYPwQlfETZeOHaEgX1B1VzKQNLC3/Aw==" },
  {
    key: "./Uniques/Weapons/Crossbow/Exceptional/Buriza-Do Kyanon.d2i",
    value: "Sk0QCIAAZQAAgoOGB4JOTq2g72EMZGSEgGEEZMg+gMIGCDHkLmRDgxNZG/Uf",
  },
  { key: "./Uniques/Weapons/Crossbow/Exceptional/Demon Machine.d2i", value: "Sk0QCIAAZQAIgiOHBwIiHOJ18XEMUFBEAqIIe/ZMwBOD8MNSOAk9Gf4D" },
  { key: "./Uniques/Weapons/Crossbow/Exceptional/Langer Briser.d2i", value: "Sk0QCIAAZQAEisOGBwLyVqbS8UEMPDzEAR8RkCHD4JERUAMFNErgUOg/" },
  {
    key: "./Uniques/Weapons/Crossbow/Exceptional/Pus Spiter.d2i",
    value: "Sk0QCIAAZACAitOGB4J0kacj7VEMUFBEBG7ccgADDLIp0haULh5jwRaEZAYXCXDKfw==",
  },
  { key: "./Uniques/Weapons/Crossbow/Normal/Doomslayer.d2i", value: "Sk0QCIAAZQAAIocnBgJHgd+h8WEEUFDEgRcRyJCZgnSRcRr9Bw==" },
  { key: "./Uniques/Weapons/Crossbow/Normal/Hellcast.d2i", value: "Sk0QCIAAZQAEgoYnBgJUPSoM71EEZGREBChQJhhxIgjFg/EwogvKU+A/" },
  { key: "./Uniques/Weapons/Crossbow/Normal/Ichorsting.d2i", value: "Sk0QCIAAZQAI0oYnBgKLRly88UEEUFCEAFoEGTImyJDDDDOWdEFxkv0H" },
  { key: "./Uniques/Weapons/Crossbow/Normal/Leadcrow.d2i", value: "Sk0QCIAAZQAMwoYnBoLmOCXQ8TEEPDyEANUBFRGMGJmAQguoRpn/" },
  { key: "./Uniques/Weapons/Dagger/Elite/Fleshripper.d2i", value: "Sk0QCIAAZQAAcrMmBwLo1i6u8AETSEhEBJYs6cjqBA7JEGUahSxR/gM=" },
  { key: "./Uniques/Weapons/Dagger/Elite/Ghostflame.d2i", value: "Sk0QCIAAZQACciPGBoIueELS79EUXl5EBHjwaLCx8fHIYnNi+h8=" },
  { key: "./Uniques/Weapons/Dagger/Elite/Wizardspike.d2i", value: "Sk0QCIAAZQAKekN2BgK1bPKc8WEQNCDEhocTfSn6VvS16GuSpTFimg36Dw==" },
  {
    key: "./Uniques/Weapons/Dagger/Exceptional/Blackbog's Sharp.d2i",
    value: "Sk0QCIAAZQAAkrMmB4Klumu48KEKMBpEhcdC6wMPctBHn74usjVJumYK13ChJdl/",
  },
  { key: "./Uniques/Weapons/Dagger/Exceptional/Heart Carver.d2i", value: "Sk0QCIAAZQACkkOWBoI1HseZ8ZEKKChEBHjwKjwWRmsGcY0jrrHEORuN/gM=" },
  { key: "./Uniques/Weapons/Dagger/Exceptional/Spineripper.d2i", value: "Sk0QCIAAZQAEkkN2BgK/sx7v8YEKICCEAFUEePAqPBY2PBBTlC6jOesE/gM=" },
  { key: "./Uniques/Weapons/Dagger/Exceptional/Stormspike.d2i", value: "Sk0QCIAAZQAGkiPGBgKl3TCh77EKMDBEBEuWZAR4AKLJBhMy6JD/" },
  { key: "./Uniques/Weapons/Dagger/Normal/Gull.d2i", value: "Sk0QCIAAZQAAQnYmBwLtxDif8HECICBEgo0KgYUHFOT/" },
  { key: "./Uniques/Weapons/Dagger/Normal/Spectral Shard.d2i", value: "Sk0QSIAAZQAEIsZGBgIEmjfD8aECMDBEAqkJN5zgScGzgqcFTxrjfw==" },
  { key: "./Uniques/Weapons/Dagger/Normal/The Diggler.d2i", value: "Sk0QCIAAZQBAQpYmBwIHA3uJ8YECKCiEAFUEGTJOLK1Y6iKb8z8=" },
  { key: "./Uniques/Weapons/Dagger/Normal/The Jade Tan Do.d2i", value: "Sk0QCIAAZQACsiaXBoJir8rn8ZECMDDEBEtaRLqgOZhjjkym/wE=" },
  { key: "./Uniques/Weapons/Mace/Elite/Baranar's Star.d2i", value: "Sk0QCIAAZQAEetNGB4IkR6yhwgEQkJAEgBcBrwjIkMEIQCYjQMZGALLJJGRdjHe4/Qc=" },
  { key: "./Uniques/Weapons/Mace/Elite/Demonlimb.d2i", value: "Sk0QCIAAZQAAejMHBwI4fPfa8YESgoJEBHPmThjB8G7Ko5HnEbOLBgoKfsV/" },
  { key: "./Uniques/Weapons/Mace/Elite/Earthshifter.d2i", value: "Sk0QKIAAZAAAenPWBoINgkkZ7REYeHhEBJYshznqZBCFuniYOfR4ePBSAXgaz38=" },
  { key: "./Uniques/Weapons/Mace/Elite/Horizon's Tornado Scourge.d2i", value: "Sk0QCIAAZQAAemPGBgI3Wahk7yETgoJEBIwYt0B1MVqiGHvqofwH" },
  { key: "./Uniques/Weapons/Mace/Elite/Nord's Tenderizer.d2i", value: "Sk0QCIAAZQAGejPGBgKRjr6F8QEYbm5EBKVKbTQf7+vSuoPMkKD0YAbtwMDwHw==" },
  { key: "./Uniques/Weapons/Mace/Elite/Schaefer's Hammer.d2i", value: "Sk0QCIAAZAAMcnOHBoIAtMwM7REQAOKAlAiCBKXokyEjk6W6oIwpKlC0QeCg/w==" },
  { key: "./Uniques/Weapons/Mace/Elite/Stone Crusher.d2i", value: "Sk0QCIAAZQAIenOHBgKTuEKr8TETgoIEAJ8IQIG+kUEng4eDCPUf" },
  { key: "./Uniques/Weapons/Mace/Elite/Stormlash.d2i", value: "Sk0QCIAAZAAMcmPGBgIDtEcG7YEWgoJEBJYsZQTZdZEB8ohCkRLDFBUew6R6KP8B" },
  {
    key: "./Uniques/Weapons/Mace/Elite/The Cranium Basher.d2i",
    value: "Sk0QCIAAZQBgenPWBgLDYCW+8SEQeHgEgJwI8OBdoDBQTiylWFqx1GKpCwrRElNjgRCE/w==",
  },
  { key: "./Uniques/Weapons/Mace/Elite/Windhammer.d2i", value: "Sk0QCIAAZQAQctN2A4J28kSA8REVeF5EBHPmukARyYxZ8IT+Aw==" },
  {
    key: "./Uniques/Weapons/Mace/Exceptional/Baezil's Vortex.d2i",
    value: "Sk0QCIAAZQAAmmPGBgKu2A+N8WEJPDxEAsIIyJClWJIRWNIFZQyBocDsgQEK6j8=",
  },
  {
    key: "./Uniques/Weapons/Mace/Exceptional/Bloodtree Stump.d2i",
    value: "Sk0QCIAAZQAEmtOWAwLJ/dOf8IEJeDwEgJwI3LidMEphtMKohVESlDWBhkjGKwRA/wE=",
  },
  { key: "./Uniques/Weapons/Mace/Exceptional/Dark Clan Crusher.d2i", value: "Sk0QCIAAZQAImjPGBgJ5xuil8fEIMDBEhGHDplR3WuThtgepRY//" },
  { key: "./Uniques/Weapons/Mace/Exceptional/Earthshaker.d2i", value: "Sk0QCIAAZQBgmnOHBgKd3P/88XEJbm5EBFq0kshECXSRxQnwUgGYsUOdwn8=" },
  { key: "./Uniques/Weapons/Mace/Exceptional/Fleshrender.d2i", value: "Sk0QCIAAZQAKmjMHBwIv6mRU7zEJSEhEBGTIKowWZEkopjR1AocyiCiNKLxSAPQf" },
  { key: "./Uniques/Weapons/Mace/Exceptional/Moonfall.d2i", value: "Sk0QCIAAZQCGmtNGB4JB3QPI71EJkJBEBEuWKigWHiMWGDdzspgxA4cCswUHHp7/" },
  { key: "./Uniques/Weapons/Mace/Exceptional/Sureshrill Frost.d2i", value: "Sk0QCIAAZQCEmtMWBgIuUjTz70EJeHhEBFq0KhQWFDZ+4PQZGpkyS4CQkfkP" },
  {
    key: "./Uniques/Weapons/Mace/Exceptional/The Gavel of Pain.d2i",
    value: "Sk0QCIAAZQBomnPWBgLgsXGI8ZEJeHhEBFCgLjAYPE40mBoLhCgkC5goMEOEGBj4Dw==",
  },
  { key: "./Uniques/Weapons/Mace/Normal/Bloodrise.d2i", value: "Sk0QCIAAZQAA0jZHB4IVDTrY8UEBkJBEBDx4eBSyWBfPGjC7Y+RQ5j8=" },
  { key: "./Uniques/Weapons/Mace/Normal/Bonesnap.d2i", value: "Sk0QCIAAZQAC0hZWBwLnYwWU8XEBeHhEBJYsT0CtgNJjBBHqPw==" },
  { key: "./Uniques/Weapons/Mace/Normal/Crushflange.d2i", value: "Sk0QCIAAZQAG0hY2BoJVNfTL8TEBeHgEgJcIPHicIIsSyGKIQv8B" },
  { key: "./Uniques/Weapons/Mace/Normal/Felloak.d2i", value: "Sk0QCIAAZQAIMsYmBoI80NTs7+EAMDBEBChQThilcINhgCBK4D8=" },
  { key: "./Uniques/Weapons/Mace/Normal/Ironstone.d2i", value: "Sk0QCIAAZQAKcofWBoIbaeHp8WEBbm4EAJUIlixNsERGoMB/" },
  { key: "./Uniques/Weapons/Mace/Normal/Steeldriver.d2i", value: "Sk0QCIAAZQAOctYWBoJT8MUe8IEBeHhEBH36OGRskenC+w8=" },
  { key: "./Uniques/Weapons/Mace/Normal/Stoutnail.d2i", value: "Sk0QCIAAZQASMgc3BgI72RuO8SEBSEjEgFMEMmRGCE4U/wE=" },
  { key: "./Uniques/Weapons/Mace/Normal/The Generals Tan Do Li Ga.d2i", value: "Sk0QCIAAZQAAasYWBgKqtqfi8VEBPDxEBB48KgQWKB9G4KPQBWVJ9h8=" },
  { key: "./Uniques/Weapons/Polearm/Elite/Bonehew (Eth).d2i", value: "Sk0QCMAAZQAIcvN2A4IkWLG88TEYZGRIBKBAu8jqBIxBVMiYOUp4ePwH" },
  { key: "./Uniques/Weapons/Polearm/Elite/Bonehew.d2i", value: "Sk0QCIAAZQAEcvN2A4Jcv6Ki8TEYZGRIBKBAu8jqBIxBVMiYOUp4ePwH" },
  { key: "./Uniques/Weapons/Polearm/Elite/Stormspire.d2i", value: "Sk0QCIAAZQAAcnM3BgJzgWLH8IEQbm4EAJUI+vSlIJMRtNNFBmhjmowyQZCsqKHwHw==" },
  { key: "./Uniques/Weapons/Polearm/Elite/The Reaper's Troll.d2i", value: "Sk0QCIAAZQAEcjOHAwLsSaX68GEUgoJEBHjwbBCwOODx2LI0Z6OQseCK0H8=" },
  {
    key: "./Uniques/Weapons/Polearm/Elite/Tomb Reaver.d2i",
    value: "Sk0QKIAAZAAAcgMXBgIgA+x07aESgoJMF2gWjIARox59UGhPkKUgW0HWgoyPd5sAUFhx/Ac=",
  },
  { key: "./Uniques/Weapons/Polearm/Exceptional/Athena's Wrath.d2i", value: "Sk0QCIAAZQAAkjOHAwJz18rn8TELgoKEgFcEWrSmdF1k2BBtyH8=" },
  { key: "./Uniques/Weapons/Polearm/Exceptional/Blackleach Blade.d2i", value: "Sk0QCIAAZQAEkmP3BgLbjJWS8SELZGREBEaMeCCyyJYlYwUSBW3Kfw==" },
  {
    key: "./Uniques/Weapons/Polearm/Exceptional/Grim's Burning Dead.d2i",
    value: "Sk0QCIAAZQAIknM3BoK7HbCs8GELbm4EBAoRaNGaoM+JLxiD6JwgpmhbZOjI/gM=",
  },
  { key: "./Uniques/Weapons/Polearm/Exceptional/Husoldal Evo.d2i", value: "Sk0QCIAAZQAMkoOWA4LB8IvF8VELbm5EBGTIJuhzgcIAUiJ3QdUJ/Ac=" },
  {
    key: "./Uniques/Weapons/Polearm/Exceptional/Pierre Tombale Couant.d2i",
    value: "Sk0QKIAAZAAEkgMXBoKtBhp67UELgoJEo9sUbozMh+ECg4ESgRu3Ccj8Bw==",
  },
  { key: "./Uniques/Weapons/Polearm/Exceptional/The Meat Scraper.d2i", value: "Sk0QKIAAZAAAkiN2A4KnvmlC7RELZGREBGTIush4KA7JoPTxCgHYfw==" },
  { key: "./Uniques/Weapons/Polearm/Normal/Dimoaks Hew.d2i", value: "Sk0QCIAAZQAEIhYmBwJQAcSk8QEDZGSEgFcEMmQ+CKAL6j8=" },
  { key: "./Uniques/Weapons/Polearm/Normal/Soul Harvest.d2i", value: "Sk0QAIAAZQAAMjeWBwLZXw4U8SEDgmgEKEXo0WNCCyeMUhitMGph5ENxyPMf" },
  { key: "./Uniques/Weapons/Polearm/Normal/Steelgoad.d2i", value: "Sk0QAIAAZQAAavdWB4J5cRyn8REDZEREMGJkggcnblLcrLhpcZOkA863kec/" },
  { key: "./Uniques/Weapons/Polearm/Normal/The Battlebranch.d2i", value: "Sk0QCIAAZQAMAheGB4JJRO+s8TEDgoKEAFUEI0YmkMHj0EX2Hw==" },
  { key: "./Uniques/Weapons/Polearm/Normal/The Grim Reaper.d2i", value: "Sk0QAIAAZQCAejc3BoIktLUj8FEDblhEoEDhwuOjUCfQiPwf" },
  { key: "./Uniques/Weapons/Polearm/Normal/Woestave.d2i", value: "Sk0QCIAAZQAQghbGBoI//dSD8UEDbm5EBBQoskScQZ0AHqehcEhmSfYf" },
  { key: "./Uniques/Weapons/Scepter/Elite/Heaven's Light.d2i", value: "Sk0QCIAAZQAAcjM3BoLWOz9h7zEXZGRIBJYsp2xZrguKTghRaBHlPw==" },
  { key: "./Uniques/Weapons/Scepter/Elite/Ironward.d2i", value: "Sk0QCIAAZQACcnM3BwI8hz3P8cEXjIxEBJEiRRw0oOB18bxJc4cbopClDC8MAP4H" },
  { key: "./Uniques/Weapons/Scepter/Elite/The Reedeemer.d2i", value: "Sk0QCIAAZQAGcjM3BoIXCM0E8FEYZGREBJYsp0xZbgvKmjJcw4dvGNEJ5XH4Hw==" },
  {
    key: "./Uniques/Weapons/Scepter/Exceptional/Hand of Blessed Light.d2i",
    value: "Sk0QCIAAZAAAknM3B4KzUIBf4iEJjIxEBFCgKlAWWhsePvBgypQF15Thmjy6g8cYkUfhPw==",
  },
  {
    key: "./Uniques/Weapons/Scepter/Exceptional/The Fetid Sprinkler.d2i",
    value: "Sk0QCIAAZQAEkhM3B4JtWeFd8REJeHhEBF++JiBT4bGQyZFZZmSmTMaCKBTGgisK/wE=",
  },
  {
    key: "./Uniques/Weapons/Scepter/Exceptional/Zakarum's Hand.d2i",
    value: "Sk0QCIAAZQAGkjM3BoJR1LXx8QEJZGREBG7cNihwePCB6CJbI0dr7GhOY8UOhv8=",
  },
  { key: "./Uniques/Weapons/Scepter/Normal/Knell Striker.d2i", value: "Sk0QCIAAZQAAMjcGBwKRiC3z8fEAZGREgpcIUKBMGOGEUQsjRJn/" },
  { key: "./Uniques/Weapons/Scepter/Normal/Rusthandle.d2i", value: "Sk0QCIAAZQACcjY3BoIZ0fUP7wEBeHhEBB48KgwWDiMCHogpy5ozW/NmeqD8Bw==" },
  { key: "./Uniques/Weapons/Scepter/Normal/Stormeye.d2i", value: "Sk0QCIAAZQAEcjcHBwJD989CwREBjIxEBDx4ZAQG2BgosKQEXeOma+xsTZ78Bw==" },
  { key: "./Uniques/Weapons/Spear/Elite/Arioc's Needle (Eth).d2i", value: "Sk0QCMAAZQAIcjMnBwKEPiKa8eEXPDxEBHPmckw2mb4usjn/sJHsPw==" },
  { key: "./Uniques/Weapons/Spear/Elite/Arioc's Needle.d2i", value: "Sk0QCIAAZQAMcjMnBwI9Cueb8eEXPDxEBHPmckw2mb4usjn/sJHsPw==" },
  { key: "./Uniques/Weapons/Spear/Elite/Steelpillar.d2i", value: "Sk0QCIAAZQAAcgN3AwIlb+vi8WEVMjIEBCgRCBLs0qJDQZTB9D8=" },
  { key: "./Uniques/Weapons/Spear/Elite/Viperfork.d2i", value: "Sk0QCIAAZQAEciMmB4JbFC/78TEUODhEBHjwJujTgixHU03p62I0lkzx+A8=" },
  { key: "./Uniques/Weapons/Spear/Exceptional/Hone Sundan.d2i", value: "Sk0QCIAAZQAAkjNHB4K0jbVa8fEKODhMBGTILlAYUIha/JT/" },
  { key: "./Uniques/Weapons/Spear/Exceptional/Kelpie Snare.d2i", value: "Sk0QCIAAZQAEkkMnBwKPJy6f8dEKRkYEAJUItGhd8DDITpBZWmJT/gM=" },
  { key: "./Uniques/Weapons/Spear/Exceptional/Soulfeast Tine.d2i", value: "Sk0QCIAAZQAQkiMmB4Iz17zv8eEKODhEBF++JujD4+DjkORhC5Qm1H8=" },
  {
    key: "./Uniques/Weapons/Spear/Exceptional/Spire of Honor.d2i",
    value: "Sk0QCIAAZQAMkgOXAwJulIje8QELMjIEhAwRkCG7QGFAKZGz3BjUnRa8MAA2j/kP",
  },
  { key: "./Uniques/Weapons/Spear/Exceptional/The Impaler.d2i", value: "Sk0QCIAAZQAAmjMnB4LXbGjP8cEKPDxEBFWqJljSBbXGwdZM6Jx1AodQ/wE=" },
  { key: "./Uniques/Weapons/Spear/Normal/Bloodthief.d2i", value: "Sk0QAIAAZQCEKibnBgLi6pEv8NECOBwAUDmgI4IMGTwSh0b/AQ==" },
  { key: "./Uniques/Weapons/Spear/Normal/Lance of Yaggai.d2i", value: "Sk0QCIAAZQAAOgdHB4JSoQvK8eECODjEiaAUQSuCWgTJCHhwgujC+w8=" },
  { key: "./Uniques/Weapons/Spear/Normal/Razortine.d2i", value: "Sk0QCIAAZQAIQieXBgLZH67K8cECRkYEgBcBqAgyZHSR0ZFZyvwH" },
  { key: "./Uniques/Weapons/Spear/Normal/The Dragon Chang.d2i", value: "Sk0QCIAAZQCAOgcnBwITodWV8bECPDzEhBEuKDAGDGQxPXj+Aw==" },
  { key: "./Uniques/Weapons/Spear/Normal/The Tannr Gorerod.d2i", value: "Sk0QCIAAZQCICpe2BgJNI/KG8fECMjLEAR8RyJCZwMOJIBQPxoWNLPcf" },
  { key: "./Uniques/Weapons/Staff/Elite/Mang Song's Lesson.d2i", value: "Sk0QCIAAZQAAYnM3BwIUazPR8SEUNDTEBoU0sj9t+uD04enDfw==" },
  { key: "./Uniques/Weapons/Staff/Elite/Ondal's Wisdom.d2i", value: "Sk0QCIAAZAAMYjM2BwL6vPQB7UEYRkZEAOkHGI1AqtxIE/zD/w==" },
  {
    key: "./Uniques/Weapons/Staff/Exceptional/Chromatic Ire.d2i",
    value: "Sk0QCIAAZQAAgjM2BwIdO8Qo8ZELRkbECaMURiuMWhgxCadkaVBremTNj6wJEkD0Pw==",
  },
  { key: "./Uniques/Weapons/Staff/Exceptional/Razorswitch.d2i", value: "Sk0QCIAAZQACgjM3BwKTjHO28HELKCjEATgJnkc8J8hSkK0ga0Hm5JFG9if/AQ==" },
  { key: "./Uniques/Weapons/Staff/Exceptional/Ribcracker.d2i", value: "Sk0QCIAAZQAEgsM2BwJ686g074ELPDyEgBcEMhEoUrzgYQh+cEMSsi7GMUZEsv8=" },
  { key: "./Uniques/Weapons/Staff/Exceptional/Skullcollector.d2i", value: "Sk0QCIAAZQAGgnM3BwI0T5/+8bELZGREE++PFFHgIf8B" },
  { key: "./Uniques/Weapons/Staff/Exceptional/Warpspear.d2i", value: "Sk0QCIAAZQAKgiM2B4IPlRO18aELUFAECH1TsjUrtsbG1ujYnP8B" },
  { key: "./Uniques/Weapons/Staff/Normal/Bane Ash Short Staff.d2i", value: "Sk0QCIAAZQAAMjdHBwI5qc+U8GEDKChEAp8IPHicIINBYKALag2Jrimh/w==" },
  {
    key: "./Uniques/Weapons/Staff/Normal/Serpent Lord Long Staff.d2i",
    value: "Sk0QCIAAZQACwjZHB4Lp0CrJ8XEDPDxEApUIKFC0IMuBAgpLfJCzDB3Zfw==",
  },
  {
    key: "./Uniques/Weapons/Staff/Normal/Spire of Lazarus Gnarled Staff.d2i",
    value: "Sk0QCIAAZQAEMjZHBwLUGaow8IEDRkZEgNeGFRFFij4ZAQdTkjUqtiaG1tTIfw==",
  },
  {
    key: "./Uniques/Weapons/Staff/Normal/The Iron Jang Bong War Staff.d2i",
    value: "Sk0QCIAAZQAGcjdHB4JSTsAW76EDZGREBDJkPqBgSpQGtYbF1rjQGhi6Y+Q/",
  },
  {
    key: "./Uniques/Weapons/Staff/Normal/The Salamander Battle Staff.d2i",
    value: "Sk0QCIAAZQAKIjZHBwIeOga975EDUFDECSgYDyDWlNiaF1ozI36i/w==",
  },
  { key: "./Uniques/Weapons/Sword/Elite/Azurewrath.d2i", value: "Sk0QCIAAZABoejMmB4JmV4wC7dEBAAKASgCVANUAVQSHDmno07ehT78vy3WR/cmlO+0/" },
  { key: "./Uniques/Weapons/Sword/Elite/Bloodmoon.d2i", value: "Sk0QCIAAZQAAejMnBgKFELDL8RESQEBEBIIEeTysNA7JmD1VJCT8Bw==" },
  { key: "./Uniques/Weapons/Sword/Elite/Djinnslayer.d2i", value: "Sk0QCIAAZQACejPXBgIwPJjC7yESLCxIBHjwYOjT92HIo2oPa5EO/wE=" },
  { key: "./Uniques/Weapons/Sword/Elite/Doombringer.d2i", value: "Sk0QCIAAZQAEeiN2AwLSlXGu8UEQUFBEBH36KngWyBc8DGQeBybeHR6YGhuQQPwH" },
  { key: "./Uniques/Weapons/Sword/Elite/Flamebellow.d2i", value: "Sk0QCIAAZQAGenM2BwKkb1+07xEWZGQEAJoBqgjw4MFIFx8mheQnc+QxBoXD+A8=" },
  { key: "./Uniques/Weapons/Sword/Elite/Frostwind.d2i", value: "Sk0QCIAAZQAIesM2BwLPrfVM79EWWFhEBHPmbLSbt+zSCmPOsdMQofT4Dw==" },
  { key: "./Uniques/Weapons/Sword/Elite/Lightsabre.d2i", value: "Sk0QCIAAZQBgejMmBwKwqxjs8TEQACICMmQVFAseGQEyNHjw+Dhk2S6oOSFlhlE1FP4D" },
  { key: "./Uniques/Weapons/Sword/Elite/The Grandfather.d2i", value: "Sk0QCIAAZQAEcnNGBgLxkjzX8VEQZGAEAJoANAG0AbQDcCLo03fHCKbaqP8=" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Bing Sz Wang.d2i", value: "Sk0QCIAAZQAEkjPWBoJXkgqY8TEKZGQEAJoIoEDZkGG0tMXIkDA2AFH4Dw==" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Blade of Ali Baba.d2i", value: "Sk0QCIAAZQAGkmM2BoL7PUn+8NEJQECIgFeClwh48Lyj4CH/AQ==" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Bloodletter.d2i", value: "Sk0QCIAAZQAIkjM3BwL4byd78aEJMGxEBEaMJmhRgbHQ4oFI4tEFteYP11yaJs9/" },
  {
    key: "./Uniques/Weapons/Sword/Exceptional/Cloudcrack.d2i",
    value: "Sk0QCIAAZQAKkiOWA4JRMDmo8VEKUFBEBGTIPqBAhZIRwJPFAD1eGQDipQEgY0cehv8=",
  },
  { key: "./Uniques/Weapons/Sword/Exceptional/Coldsteel Eye.d2i", value: "Sk0QCIAAZQAMkjPXBgKe9o7r8bEJLJBEBH36fBiSyHRBxQk0klny/Ac=" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Crainte Vomir.d2i", value: "Sk0QCIAAZQAOkiODBoJdJQq38SEKWFhEBGTISCh0MYJB4dFZGv0H" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Ginther's Rift.d2i", value: "Sk0QCIAAZQAQkjMmBwLYamuo8OEJKHhEBEuWRjA0ZPAkQeki40f9Bw==" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Headstriker.d2i", value: "Sk0QCIAAZQAAmiM2B4LFyai88fEJQEAEgJcIlizVCWhD9DH/AQ==" },
  { key: "./Uniques/Weapons/Sword/Exceptional/Hexfire.d2i", value: "Sk0QCIAAZQAEmjMnBgKySiWu8cEJQEBEBFCgKowWUCeWUKg5/WTMDB9ISP4D" },
  {
    key: "./Uniques/Weapons/Sword/Exceptional/Plague Bearer.d2i",
    value: "Sk0QCIAAZQAGmsM2BwI4lYIp7wEKWFhEBEuWKigWWi2+cgAGGLI17mqM4KLwHw==",
  },
  {
    key: "./Uniques/Weapons/Sword/Exceptional/Swordguard.d2i",
    value: "Sk0QSIAAZQBgmnNGBoKwmZ+W8XEKZGREBFq0KFAgyIRAPmGUwmiFUQujLTJjUHI8a+h/",
  },
  { key: "./Uniques/Weapons/Sword/Exceptional/The Atlantian.d2i", value: "Sk0QCIAAZQBkmnNHBoJAo3mP7xEKWCAFABgBrAGoCPr0fahCErIp0x0j/wE=" },
  { key: "./Uniques/Weapons/Sword/Exceptional/The Vile Husk.d2i", value: "Sk0QCIAAZQBmmnM2B4JGYcsI8UEKZGREBGTIWpDlUE01S8YCIQz0eHvUfw==" },
  {
    key: "./Uniques/Weapons/Sword/Exceptional/Todesfaelle Flamme.d2i",
    value: "Sk0QCIAAZQBommMmBgLkLc348GEKZGREBFCgTmjBkEH2SDHMeEHBTJmBgoKZQkNLy38=",
  },
  { key: "./Uniques/Weapons/Sword/Normal/Blacktongue.d2i", value: "Sk0QCIAAZQAAIjZ3BwIMgXMt8UECUFBEBB48JsjQgiwHMMBYqhP4Dw==" },
  { key: "./Uniques/Weapons/Sword/Normal/Blood Crescent.d2i", value: "Sk0QCIAAZQACMjfWBoKkpeAl76EBLCzEgRcRoEA5EZQiaEVQiyAejyzYZXQo9B8=" },
  { key: "./Uniques/Weapons/Sword/Normal/Culwens Point.d2i", value: "Sk0QCIAAZQAEcjdHBoI1V6fT8QECWFhEBChQJvDQBTUG5cboT/4D" },
  { key: "./Uniques/Weapons/Sword/Normal/Gleamscythe.d2i", value: "Sk0QCIAAZQAGYsY2BgIFxL/E8MEBQEBEAp8IZMh88ICNgQIyWa4L6j8=" },
  { key: "./Uniques/Weapons/Sword/Normal/Griswold's Edge.d2i", value: "Sk0QCIAAZQAIIjZHBgI+GqA38eEBQEAEAJYIePBMIAMGQ4YogS6e/w==" },
  { key: "./Uniques/Weapons/Sword/Normal/Hellplague.d2i", value: "Sk0QCIAAZQAMwjZHBgI0Z7TD7/EBWFhEBChQYGQsyQEDGJZ4FHwU/ET/AQ==" },
  { key: "./Uniques/Weapons/Sword/Normal/Kinemils Awl.d2i", value: "Sk0QCIAAZQAQcpY2BwJY85H+7zECZGREApoIZMhMsASGAYo1Zvwf" },
  { key: "./Uniques/Weapons/Sword/Normal/Ripsaw.d2i", value: "Sk0QCIAAZQAAasYmBoLNGqu18VECZGREBDJkLDwwPHwYDkH/Aw==" },
  { key: "./Uniques/Weapons/Sword/Normal/Rixot's Keen.d2i", value: "Sk0QCIAAZQASMjdHBgKouxI28JEBMDBEBDJkKhQfRpDF7qBAlPkP" },
  { key: "./Uniques/Weapons/Sword/Normal/Shadowfang.d2i", value: "Sk0QCIAAZQAEKoM2BwI7eqyY8RECWFhEBDJkVhjZUPBgySPhI5FF/gM=" },
  { key: "./Uniques/Weapons/Sword/Normal/Skewer of Krintiz.d2i", value: "Sk0QCIAAZQAGOicmBwKD/taK8LEBQEAEABUBqggyZFQYLBx8HOb8Dw==" },
  { key: "./Uniques/Weapons/Sword/Normal/Soulflay.d2i", value: "Sk0QCIAAZQAIOsbWBgJTzuL68SECZGREBDJkTtykuFlx0+KGB8GHoovnPw==" },
  { key: "./Uniques/Weapons/Sword/Normal/The Patriarch.d2i", value: "Sk0QCIAAZQCAejZHBoKVucJ58GECZGQEAJUIePCIGEYMT5DFCfwH" },
  { key: "./Uniques/Weapons/Throw/Elite/Demon's Arch.d2i", value: "Sk0QIIAAZAAAcjN3AwIY7Bs+7UEVHBwoiCBNGgz0oTwY/ZQuMhlXU/8B" },
  { key: "./Uniques/Weapons/Throw/Elite/Gargoyle's Bite.d2i", value: "Sk0QAIAAZQAAckM3B4InSJJx8QEUJCRAiWDOXA6WWNLH48FsyYCHp5/3Hw==" },
  { key: "./Uniques/Weapons/Throw/Elite/Gimmershred.d2i", value: "Sk0QAIAAZQACckMXBgI2e1bl8fEUHh7AiyBNGgzt8TK6+mzANibrIvPH8x8=" },
  { key: "./Uniques/Weapons/Throw/Elite/Lacerator.d2i", value: "Sk0QAIAAZQAEciOGAwIw5MvX8REUICCsiSBNWhcZnF+dwKGQsUGIUL/sPw==" },
  { key: "./Uniques/Weapons/Throw/Elite/Warshrike.d2i", value: "Sk0QAIAAZQAIciO2BoIp5bCv70ESKCggi6BPXxdZIxknmbEEhkw/7z8=" },
  { key: "./Uniques/Weapons/Throw/Elite/Wraithflight.d2i", value: "Sk0QAMAAZQAKcnPGBgIG0NOe8SEYICAsieDLF4+Gokc/9D8=" },
  { key: "./Uniques/Weapons/Throw/Exceptional/Deathbit.d2i", value: "Sk0QAIAAZQAAkkO3BgLXKuou8TESDAyAikCL1gTheCR8GBqh+mX/AQ==" },
  { key: "./Uniques/Weapons/Throw/Exceptional/The Scalper.d2i", value: "Sk0QAIAAZQACkkMXBgLp4J268AESHh4IioAMGQ9DF9SdFodCigj9vP8=" },
];
